### ISSUE TITLE
Token mint pallet based on specific event

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#1002]
The idea is to create a pallet that could be used in a one-way bridge. The pallet will verify a specific event on the bridged chain (for instance "burn" or "bond") and mint tokens on the home chain with the same amount.

The use cases in mind:

1. Give testnet (Rococo / Westend) tokens to people who bonded KSM on Kusama.
2. Move testnet tokens between networks (Westend -> Rococo) transition.

Issueing tokens based on tokens `bond`ed is obviously gameable, but it's rate-limitted and costly. One needs to wait for unbounding period, send some additional transactions and have the lost opportunity cost (staking rewards), so I think it's still interesting.

If the pallet was made generic enough it could be an arbitrary "if event -> then action" kind of pallet. So it should look up a particular event (or events) and then trigger some action on the home chain. There should be no ordering required or guaranteed, calls should be expected to be made by regular users that are interested.
To prevent multi-claims we can temporarily store already-claimed events and prune them at the same time the finality pallet is being pruned.

This pallet should not be based on messaging protocol, but rather just on the finality pallet.

**Comment by tomusdrw** [comment]
Another use case is deploying two one way bridges with potentially different security:
1. Fully trustless one way bridge based on this pallet (transfer to multisig -> mint)
2. Multisig based bridge to transfer tokens back on the main chain.

The advantage is that the network we bridge to only needs to support the multisig pallet and no extra bridge-specific pallets need to be added - In fact the chain is not even aware it's bridged with.
If the bridge chain is using some form of PoS and the multisig is controlled by the same set of validators (would require multisig ownership changes during authority set hand offs though) the security is essentially as high as it can be - by having tokens on the bridged chain you already trust the authorities there not to collude, same as with the multisig. Colluding on multisig transfers could also be made a slashable offence on the original chain to prevent validators from colluding only on the bridge side not the PoS chain itself.

**Comment by EmmanuellNorbertTulbure** [comment]
Obsolete
