### ISSUE TITLE
Auto-dump logs every day on testnet deployment

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#1013]
There is a script to dump logs on testnet deployment (`scripts/dump_logs.sh`), but it's currently being run manually in case there are any issues.
It would be cool to run the script before deployment and save up to `N` last days of logs for investigation, for instance in case the things get bad over the weekend and there is no one to look into that.

**Comment by HCastano** [comment]
Maybe we should look into using a log ingestion/aggregation system, like the one used by DevOps (e.g Loki). It would be a bit more robust than a cronjob + script

**Comment by svyatonik** [comment]
I have made a [script](https://github.com/parity-bridges-common-logs/test-deployment-logs/blob/bf1c7db4b22ab7b2a8a264d8d9792bbf86e6f084/grep-errors.sh) that grep logs for errors and failures + leaves full logs temporary at test deployments machine + uploads grepped versions to the https://github.com/parity-bridges-common-logs/test-deployment-logs repo. It is configured to run 3 times a day + keep 12 last log folders => so it should survive over weekend. I think this issue could be closed
