### ISSUE TITLE
Separate dispatch and payment accounts.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#1052]
After #911 we can now pay the fees both on the source chain and the target chain. Together with @apopiak and @gautamdhameja  today we were discussing that it would be interesting to separate the account that is paying the fees from the account that is used to dispatch the payload.

We should consider supporting separate payment account for both source-chain payment and target-chain payment. I imagine this will require additional signature verification to make sure we have "consent" of that particular account. Alternatively we can have some kind of mapping (similar to stash-controller), where the account can opt-in for paying for either one particular sender or multiple senders.

Perhaps this is also doable using a `proxy`, so maybe we don't need to implement anything but just provide an example of that?

**Comment by svyatonik** [comment]
irrelevant after #1376
