### ISSUE TITLE
Migrate the common files in the substrate-relay to the new crate

### ISSUE THREAD

**Issue by fewensa** [paritytech/parity-bridges-common#1055]
Hi:  I think we can migrate the common files to a new crate

includes:

- [finality_pipeline.rs](https://github.com/paritytech/parity-bridges-common/blob/1734d005175843dd3860e491b7bf63c5d5bb9221/relays/bin-substrate/src/finality_pipeline.rs)
- [finality_target.rs](https://github.com/paritytech/parity-bridges-common/blob/1734d005175843dd3860e491b7bf63c5d5bb9221/relays/bin-substrate/src/finality_target.rs)
- [headers_initialize.rs](https://github.com/paritytech/parity-bridges-common/blob/1734d005175843dd3860e491b7bf63c5d5bb9221/relays/bin-substrate/src/headers_initialize.rs)
- [messages_lane.rs](https://github.com/paritytech/parity-bridges-common/blob/1734d005175843dd3860e491b7bf63c5d5bb9221/relays/bin-substrate/src/messages_lane.rs)
- [messages_source.rs](https://github.com/paritytech/parity-bridges-common/blob/1734d005175843dd3860e491b7bf63c5d5bb9221/relays/bin-substrate/src/messages_source.rs)
- [messages_target.rs](https://github.com/paritytech/parity-bridges-common/blob/1734d005175843dd3860e491b7bf63c5d5bb9221/relays/bin-substrate/src/messages_target.rs)
- [on_demand_headers.rs](https://github.com/paritytech/parity-bridges-common/blob/1734d005175843dd3860e491b7bf63c5d5bb9221/relays/bin-substrate/src/on_demand_headers.rs)

Because this will make it easier for bridge developers to reference these files instead of copying these files to other projects. I can modify it if this is feasible

**Comment by tomusdrw** [comment]
Makes sense to me. I can also see `bin-substrate` becoming more generic to cater for use cases you might have. Would that be possible?

**Comment by fewensa** [comment]
I will do this and create a pr
