### ISSUE TITLE
Is poa-ether -> substrate bridge deployment supposed to work?

### ISSUE THREAD

**Issue by yrong** [paritytech/parity-bridges-common#1060]
when testing ether-poa -> substrate bridge deployment I failed to start the `relay-headers-poa-to-rialto` container with the script `./deployments/run.sh --no-monitoring start poa-rialto`

check logs with `docker logs deployments_relay-headers-poa-to-rialto_1 -f` error as following:
```
2021-07-19 18:01:55 +0000 INFO bridge Starting ETH â¡ SUB relay.
2021-07-19 18:01:55 +0000 DEBUG bridge Ethereum sync params: EthereumSyncParams { eth_params: ConnectionParams { host: "poa-node-arthur", port: 8546 }, sub_params:
 ConnectionParams { host: "rialto-node-alice", port: 9944, secure: false }, sub_sign: d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (5GrwvaEF...), sync_params: HeadersSyncParams { max_future_headers_to_download: 128, max_headers_in_submitted_status: 128, max_headers_in_single_submit: 32, max_headers_size_in_single_submit: 131072, prune_depth: 4096, target_tx_mode: Signed }, metrics_params: MetricsParams { address: Some(MetricsAddress { host: "0.0.0.0", port: 9616 }), registry: None, metrics_prefix: None }, instance: RialtoPoA }
[Ethereum_to_Substrate_Sync] 2021-07-19 18:01:55 +0000 DEBUG bridge Received best header number from Ethereum node: 1
[Ethereum_to_Substrate_Sync] 2021-07-19 18:01:55 +0000 DEBUG bridge Received best known header from Substrate: HeaderId(0, 0x1468e1a0fa20d30025a5a0f87e1cced4fdc393b84b7d2850b11ca5863db482cb)
[Ethereum_to_Substrate_Sync] 2021-07-19 18:01:55 +0000 DEBUG bridge Ethereum header HeaderId(0, 0x1468e1a0fa20d30025a5a0f87e1cced4fdc393b84b7d2850b11ca5863db482cb) is now Synced
[Ethereum_to_Substrate_Sync] 2021-07-19 18:01:55 +0000 DEBUG bridge Asking Substrate about incomplete headers
[Ethereum_to_Substrate_Sync] 2021-07-19 18:01:55 +0000 DEBUG bridge Going to download new header from Ethereum node: 1
[Ethereum_to_Substrate_Sync] 2021-07-19 18:01:55 +0000 DEBUG bridge Queueing new Ethereum header: HeaderId(1, 0xa7fc8ccccf8a717a491ddf992413031f1417e35ea40fd71dbbf6aa888c723a69). Queue: MaybeOrphan.
[Ethereum_to_Substrate_Sync] 2021-07-19 18:01:55 +0000 DEBUG bridge Asking Substrate node for existence of: HeaderId(0, 0xf9be83948bc066ae15b2abf43d1202658b9fdf44493c57fbecf00cf625be3e7e)
[Ethereum_to_Substrate_Sync] 2021-07-19 18:01:55 +0000 DEBUG bridge Ethereum header HeaderId(1, 0xa7fc8ccccf8a717a491ddf992413031f1417e35ea40fd71dbbf6aa888c723a69) is now Orphan
[Ethereum_to_Substrate_Sync] 2021-07-19 18:01:55 +0000 ERROR bridge Misconfiguration. Genesis Ethereum header is considered orphan by Substrate node
```
error raised here:
https://github.com/paritytech/parity-bridges-common/blob/15c8cd61cb7c8a12160f2a33febd8b73511e02ff/relays/headers/src/sync_loop.rs#L576-L584

so the question here is poa-ether -> substrate bridge deployment still supposed to work or anything required I missed?

**Comment by svyatonik** [comment]
It should work - I'll try myself later. The reason that I see from logs is that the PoA node starts with genesis header `0xf9be83948bc066ae15b2abf43d1202658b9fdf44493c57fbecf00cf625be3e7e`, while Substrate pallet thinks that it'll start with `0x1468e1a0fa20d30025a5a0f87e1cced4fdc393b84b7d2850b11ca5863db482cb`. So probably at some moment the actual hash has changed and we simply have not updated [this definition](https://github.com/paritytech/parity-bridges-common/blob/15c8cd61cb7c8a12160f2a33febd8b73511e02ff/bin/rialto/runtime/src/rialto_poa.rs#L76)

**Comment by svyatonik** [comment]
I've tried today - everything works fine. Please check that you're using latest version of images. You could simply run `./deployments/run.sh --no-monitoring update poa-rialto` instead of `./deployments/run.sh --no-monitoring start poa-rialto` for that
