### ISSUE TITLE
Use compact trie proofs for both PoA receipts and transactions

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#108]
Right now the whole set of block' PoA transactions receipts and transactions is used to prove that given transaction/receipt has been included into PoA block. We could make this proof smaller by only providing affected trie nodes.

This would make PoA -> Substrate bridge testing a bit harder, so imo this could be done after initial launch.

**Comment by tomusdrw** [comment]
Closing, since we don't plan to actively work on the PoA bridge in the near future. Happy to re-open if the outlook changes.
