### ISSUE TITLE
Upgrade Pallets to Frame V2

### ISSUE THREAD

**Issue by ferrell-code** [paritytech/parity-bridges-common#1081]
Extension of [polkadot#2882](https://github.com/paritytech/polkadot/issues/2882)

There are a number of custom Bridges pallets in this repo used in the polkadot repo and elsewhere. It is ideal to eventually have all active pallets migrated to the newest macro.

pallets using frame v1 in modules:
-  [x] dispatch
-  [x] messages
-  [x] shift-session-manager
-  [x] ethereum
-  [x] currency-exchange

**Comment by svyatonik** [comment]
all pallets are using v2 now
