### ISSUE TITLE
Need a Label for `E1-runtimemigration`

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/parity-bridges-common#1096]
Just like what you guys do in substrate.

We're going to use this on production.

Thanks!

**Comment by svyatonik** [comment]
We have `PR-breaksruntime` label for such cases, though it wasn't used that often before (we're just in the process of deploying our pallets on persistent chains). Will it work for you?

**Comment by AurevoirXavier** [comment]
Yes. If you can check that each PR from now.
Very appreciate.
