### ISSUE TITLE
Improve Test Readability

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#111]
We should strive to make tests more readable by abstracting common setup/teardown stuff into helper functions. We should also try and be explicit about what is being checked in a test with the use of intermediate variables. There's some room for improvement in places like `modules/ethereum/src/{finality, import}.rs`, but we should be checking the entire codebase.

Clean tests are not limited to the things I've suggested here, but it's just what I've noticed we could work on with the existing tests.

**Comment by tomusdrw** [comment]
Closing, since it has been here for a while and since the PoA stuff is pretty low priority now, I don't expect this being worked on any time soon.
