### ISSUE TITLE
Clean up custom types that are not needed anymore.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/parity-bridges-common#1140]
Since polkadotjs api contains some of the custom types needed for setting up the bridge, some custom types are not needed anymore. For example, the header sync and messaging stuff.

**Comment by tomusdrw** [comment]
@hbulgarini can you tak a look at this? Would be good to only have the essential types.

**Comment by tomusdrw** [comment]
CC @hbulgarini

**Comment by acatangiu** [comment]
This is obsolete AFAICT
