### ISSUE TITLE
Share data reads when several headers are imported at once

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#117]
Now when we're importing several PoA headers in single call, every header import starts from the scratch - i.e. we're creating `ImportContext`, `ValidatorsSet` and `FinalityVotes` (see #116 ). But we actually may reuse `FinalityVotes` from the parent' header import (if parent is imported in the same call) + construct `ImportContext` and `ValidatorsSet` after parent is imported (without any additional reads). This will decrease number of redundant storage reads significantly, because relay is now configured to submit 32 headers in single transaction.

**Comment by tomusdrw** [comment]
The storage reads are going to be cached anyway (coming from the overlay), so I don't think this optimization is critical. We would for sure minimize the number of host calls though.

It sounds to me like it's a "good first issue" as well, so tagging as such.

**Comment by acatangiu** [comment]
Made obsolete by https://github.com/paritytech/parity-bridges-common/pull/1210
