### ISSUE TITLE
Add custom GRANDPA RPC into node-template

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#1205]
Since our `<network>/node/service` files are mostly a copy paste of `node-template`, and the template runtime does include GRANDPA pallets and API it makes sense to include the custom GRANDPA RPC in the `node-template` service file as well, hence simplifying our upgrade process.

Note this should be done in the Substrate repository.

**Comment by EmmanuellNorbertTulbure** [comment]
Obsolete?
