### ISSUE TITLE
Refresh Rococo<>Wococo runtime integration

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#1213]
The Rococo<>Wococo bridge integration was removed in https://github.com/paritytech/polkadot/pull/3780. We should:
1. Update the `git subtree` to reference the latest commit from https://github.com/paritytech/parity-bridges-common/tree/polkadot-staging branch.
2. Restore runtime integrations.
3. Run bechmarks again or use existing weights (see #391)
4. Use filters similar to Polkadot<>Kusama integration see (https://github.com/paritytech/polkadot/tree/bridges-integration-2)

**Comment by svyatonik** [comment]
1+2 are done in https://github.com/paritytech/polkadot/pull/4427 + https://github.com/paritytech/polkadot/pull/4452 . Re weights - imo we may use existing weights for  R<>W, but for P<>K we'll need to integrate our benchmarks to polkadot/kusama runtime. 

So now we're in waiting-for-Rococo/Wococo update state. IDK if we have to initiate it ourselves?

**Comment by svyatonik** [comment]
Rococo <> Wococo bridge is running
