### ISSUE TITLE
Asset transfer pallet

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#1221]
A pallet that allows transferring of native tokens (`balances` pallet or `assets`) of the Source chain to the Target chain.

The idea is to "lock" the tokens in a specific account that can only be accessed by the bridge (or bridge pallet) on the Source chain and send a message to the Target chain that a wrapped version of that tokens should be minted.

The redeem process (Target -> Source transfer) is expected to burn the wrapped tokens on the Target chain and then send a message that will transfer the same balance from the bridge account on the Source chain.

While the process above describes a situation where the assets are existing directly on the Source chain, ideally if this was configurable so that the wrapped tokens can be minted on a parachain connected to the Target chain (think Statemine / Statemint).

Related #992

**Comment by tomusdrw** [comment]
![Untitled Diagram (1) drawio](https://user-images.githubusercontent.com/581548/148216568-f0695ede-a63a-4b03-9dee-79ed7b15ed25.png)

**Comment by svyatonik** [comment]
IIUC this is what XCM teleport does. Irrelevant after #1376
