### ISSUE TITLE
Dynamic Bridging

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#1225]
With BEEFY+MMR (#1223) light client it should now be possible to easily add new bridges since the amount of configuration should be minimal (BEEFY+MMR would provide unified types and crypto for all chains despite using different header formats).

This issues is an extension of #1223 to make the pallet support dynamic bridging by default, i.e. adding a new bridge should not require adding a new pallet nor any form of runtime upgrade, but rather it should be possible by the Governance (or any other on-chain component/entity) to add the bridge just by setting the starting block details and the expected BEEFY Validator Set.

The issue is both about the Runtime part and the Relayer part, but in the future it should be split.

**Comment by EmmanuellNorbertTulbure** [comment]
I do not think this is the case anymore with our XCM design.

**Comment by svyatonik** [comment]
It is potentially relevant, but not in the nearest future. Let's keep it open for a while
