### ISSUE TITLE
GRANDPA light client replica pallet

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#1228]
The idea is to build an alternative `pallet-bridge-grandpa` (or a variant of that) in which the finality proofs are not submitted directly (I guess they could though?) but rather are replicated from another trusted source.

An example use case would be to have a "primary" pallet on the relay chain (or some other parachain we trust) and just replicate the same data on a local version of the pallet. The data would be queried for instance by XCM queries or some form of broadcasting over XCM (i.e. parachain "subscribes" to the primary pallet info broadcast) or some additional mechanism of presenting a proof of expected data. This would allow running delivery pallet locally on a parachain without the need of having to maintain an expensive light client pallet. This way parachains could create their own delivery channels with parachains in the bridged ecosystem, but the consensus light client would be shared (either on the relay chain or on some special parachain).

**Comment by acatangiu** [comment]
Closing this as obsolete. We are no longer using delivery pallets, but using native XCMv3 support to address various parachains across the bridge. Target and source paras don't need light-clients (or any other mechanism to follow each others' consensus). The bridge is responsible for crossing consensus systems between the two ecosystems, XCM is then transparently used.
