### ISSUE TITLE
Automate customizing Millau service based on upstream template

### ISSUE THREAD

**Issue by acatangiu** [paritytech/parity-bridges-common#1233]
Millau `node/src/service.rs` is actually Substrate's node-template `node/src/service.rs` with a few customizations on top:
- custom RPCs
- BEEFY gadget

Add a script to automate applying Millau customizations on top of a copied Substrate node-template service file. I think even a simple git patch file should work well.

_This is impractical to do for Rialto since Rialto is based on Polkadot which has a huge service file. In Rialto's case it's easier to manually edit than try to reliably automate such a big diff._

**Comment by EmmanuellNorbertTulbure** [comment]
Closing this. Please reopen if needed!
