### ISSUE TITLE
Consider adding Loki to our test deployment

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#1236]
So that it's easier to query the logs from the running nodes.

**Comment by lovelaced** [comment]
Where is your test deployment?

**Comment by tomusdrw** [comment]
> Where is your test deployment?

It's in Test Installations, based on the `docker-compose` file in `deployments`.

**Comment by EmmanuellNorbertTulbure** [comment]
Already Done!
