### ISSUE TITLE
Reenable Grafana at test deployments

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1354]
Right now prometheus + grafana are working well on our test deployments, but we can't access Grafana UI. This is probably linked to the fact that DNS records points to some old IP and IP changes every time our VM is stopped.

So the plan is:
- [x] add static IP to our VM;
- [x] fix DNS records - I've started working on that yesterday, but had to switch to another task.

**Comment by EmmanuellNorbertTulbure** [comment]
@svyatonik is this not done?
