### ISSUE TITLE
Some fixes for new jsonrpsee version

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1355]
- [x] check if we need to migrate to new proc-macro based subscriptions mechanism: https://github.com/paritytech/jsonrpsee/blob/master/proc-macros/src/lib.rs#L231-L262 for subscriptions we use;
- [x] new proc macro requires that all its generic params need to implement `Serialize` + `Deserialize`, which isn't true for `Chain`, hence long-lines like [this one](https://github.com/paritytech/parity-bridges-common/pull/1353/files#diff-4c85e463b9a0cbf82ee5f1ee88fe1dcfce081107a76ce2b421c45980e95c247bR271-R279). Find a better solution for this

**Comment by niklasad1** [comment]
> new proc macro requires that all its generic params need to implement Serialize + Deserialize, which isn't true for Chain, hence long-lines like [this one](https://github.com/paritytech/parity-bridges-common/pull/1353/files#diff-4c85e463b9a0cbf82ee5f1ee88fe1dcfce081107a76ce2b421c45980e95c247bR271-R279). Find a better solution for this

https://github.com/paritytech/jsonrpsee/issues/696 ^^, ideas are very welcome :)

**Comment by niklasad1** [comment]
@svyatonik https://github.com/paritytech/jsonrpsee/blob/master/examples/examples/proc_macro_bounds.rs#L53-#L57 should help you to get started
