### ISSUE TITLE
Use different XCM configuration on Wococo

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1401]
Before proceeding to KusamaBridgeHub <> PolkadotBridgeHub bridge, we'll need to have (almost) the same code deployed on RococoBridgeHub <> WococoBridgeHub. The problem is that the runtime is shared between Rococo and Wococo. In bridges we solve that by adding second instance of our pallets - first instance is active on Rococo and the other one on Wococo. It'd be great if we could use XCM pallet to send XCMs between Rococo and Wococo, but it doesn't support additional instances.

To me it looks like the only thing that needs to be changed is [this line](https://github.com/paritytech/polkadot/blob/21323b7d2e3c19e149d2f24b51c7bada4782a0c5/runtime/rococo/src/xcm_config.rs#L40). So probably change `const` to `storage`? Or use conditional compilation and build different runtimes for Rococo and Wococo? Some other solution?

**Comment by acatangiu** [comment]
Opened a [sister issue in polkadot repo](https://github.com/paritytech/polkadot/issues/5584) for visibility and ideas.

**Comment by svyatonik** [comment]
https://github.com/paritytech/polkadot/pull/6007

**Comment by bkontur** [comment]
@svyatonik 
I guess, this is a obsolete issue, because we dont need to modify Rococo runtime,
and for the BridgeHub runtime I needed to hack this also, but I was able to do it like this:
https://github.com/paritytech/cumulus/blob/bridge-hub-rococo-wococo/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs#L55

```
impl Get<NetworkId> for RelayNetwork {
	fn get() -> NetworkId {
		match u32::from(ParachainInfo::parachain_id()) {
			bp_bridge_hub_rococo::BRIDGE_HUB_ROCOCO_PARACHAIN_ID => NetworkId::Rococo,
			bp_bridge_hub_wococo::BRIDGE_HUB_WOCOCO_PARACHAIN_ID => NetworkId::Wococo,
			para_id => unreachable!("Not supported for para_id: {}", para_id),
		}
	}
}
```

so, can we close this now, or is there anything else?

**Comment by svyatonik** [comment]
> @svyatonik I guess, this is a obsolete issue, because we dont need to modify Rococo runtime, and for the BridgeHub runtime I needed to hack this also, but I was able to do it like this: https://github.com/paritytech/cumulus/blob/bridge-hub-rococo-wococo/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/xcm_config.rs#L55
> 
> ```
> impl Get<NetworkId> for RelayNetwork {
> 	fn get() -> NetworkId {
> 		match u32::from(ParachainInfo::parachain_id()) {
> 			bp_bridge_hub_rococo::BRIDGE_HUB_ROCOCO_PARACHAIN_ID => NetworkId::Rococo,
> 			bp_bridge_hub_wococo::BRIDGE_HUB_WOCOCO_PARACHAIN_ID => NetworkId::Wococo,
> 			para_id => unreachable!("Not supported for para_id: {}", para_id),
> 		}
> 	}
> }
> ```
> 
> so, can we close this now, or is there anything else?

Most probably :) But I wonder - how the routing would work for XCM messages between Rococo/Wococo/Rockmine/Wockmine? I mean - they need some global location, right? Something like `GlobalConsensus/Rococo/Parachain(1000)` and `GlobalConsensus/Wococo/Parachain(1000)`. But Rococo/Wococo are sharing the same XCM configuration, right (so they're most probably `GlobalConsensus/Rococo)`? But that's just my impression - please correct me if I'm wrong :)

**Comment by svyatonik** [comment]
@bkontur ^^^ feel free to close this if you think we don't need to do anything here

**Comment by bkontur** [comment]
ok, closing, I am almost 100%-sure that we dont need this
