### ISSUE TITLE
Bridge (Relay) state dashboard

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#141]
Built for instance using https://redash.io/
Might require exposing some server endpoints from the relayer or to add some reporting to things like Prometheus or Telemetry.

Things that would be good to see:
- Latest PoA Block (Foreign Chain)
- Latest Substrate Block (Home Chain)
- Latest foreign chain block on home chain (and vice-versa)
- Last relayed block (transaction send) (both directions)
- Uptime
- Any internal relayer metrics we would like to see

**Comment by svyatonik** [comment]
I'm closing this - we now have dashboard for `eth-to-sub` and `eth-exchange-sub`. Other dashboads may be added under separate  issues/PRs.
