### ISSUE TITLE
Restore reinit-bridge relay subcommand

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1492]
I've removed it in #1491, since it has only been implemented for obsolete Kusama<>Polkadot bridge. Once we'll have Rococo/Wocococ or Kusama<>Polkadot hub<>hub bridge, we shall recover it.

**Comment by bkontur** [comment]
@svyatonik 
Slava, what is this reinit-bridge about? I saw few mentions about `halt_operations/resume_operations`.

Do we need it for Rococo<>Wococo bridge hubs?
If so, I would change at least Milestone

**Comment by svyatonik** [comment]
@bkontur I write some description in the original PR: #1315. The idea is that this is the "safe" way to reinitialize our (GRANDPA) bridge pallet. TLDR: if the pallet has been halted due some reason and GRANDPA validators set has changed (maybe multiple times), then the old validators may craft valid GRANDPA justification and submit it to our pallet, effectively switching it to other (finalized) source chain fork. This subcommand is a "solution" for this problem - it greps source chain for validators set change blocks, packs them into a single (utility batch) transaction, appends "resume" and "halt" operations to the begin and the end of the batch and submits to the bridge pallet. So we are not simply resuming pallet operation and let anyone submit transactions, but instead we only allow owner to do that until we are sure that the actual GRANDPA validators set is submitted.

**Comment by svyatonik** [comment]
@bkontur Don't bother about this issue for now :)

**Comment by bkontur** [comment]
@svyatonik 
aha, ok, make sense, thank you, just wanted to know :)

**Comment by bkontur** [comment]
@svyatonik 
and what about possibility just to "clear/flush" bridge pallets state, to be able start again from the begining? (e.g. for testing purposes)

For example, after deployment to real Rococo/Wococo parachains, I would like to start relaying again from the first header?
Can I do it somehow?

**Comment by svyatonik** [comment]
@bkontur There's an open issue for that (#490), but we haven't implemented it (yet?). Right now imo it is better to avoid making any optional complex changes to the **audited** pallets (GRANDPA and messages), so probably working on that right now is not the best moment :)

> For example, after deployment to real Rococo/Wococo parachains, I would like to start relaying again from the first header?
Can I do it somehow?

On most chains (with governance pallets or with sudo pallets) you may ask governance/sudo to remove storage entries. For our case (common good parachains) - I don't know how to do that tbh (worth exploring in the case something would go wrong). But there should be a way - iiuc still using relay chain governance? But anyway - syncing from the scratch is not our goal - we'll deploy pallets, initialize pallets with most recent headers and start running relays + watch for alerts. If some chain will be restarted - then yes, we'll need to solve this issue

**Comment by bkontur** [comment]
@svyatonik 
ok, ok, sure, thank you, just asking :)

**Comment by svyatonik** [comment]
Given that we gonna use governance to make all sudo-level calls, this is no longer actual
