### ISSUE TITLE
Switch to HaulBlobExporter and BridgeBlobDispatcher from polkadot repo

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1576]
The fact that these types can't be used from outside is a bug. Right now we have a copy in the `bridge-runtime-common` crate. This copy shall be removed and the original XCM v3 PR shall be fixed so that the "all pub types in universal_exports.rs should be reexported from lib.rs".

**Comment by bkontur** [comment]
@svyatonik 
Slava, I would love to take this as a good start to dive into xcm bridge messaging, ok?

**Comment by svyatonik** [comment]
@bkontur 
Sure, imo it involves three steps:
1) opening separate PR `some-branch` -> `gav-xcm-v3` with "all pub types in universal_exports.rs should be reexported from lib.rs". We may also ask if an isolated commit directly to the `gav-xcm-v3` would work here;
2) updating our refs to the latest `gav-xcm-v3`
3) actually using those types. TBH I'm not sure if they are currently used in Rialto/RialtoParachain<>Milau - I've had too many troubles with using them back when we've been switching to the XCM messaging. This may take a while and require many changes. In any case - if you'll have troubles here, let's chat/discuss later

**Comment by EmmanuellNorbertTulbure** [comment]
@bkontur status on this one?

**Comment by EmmanuellNorbertTulbure** [comment]
When closing, the questions from the PR should be transferred into issue(s).

**Comment by bkontur** [comment]
@EmmanuellNorbertTulbure PR is closed and I guess, the only thing, which is not in any issue, is just this test: https://github.com/paritytech/parity-bridges-common/pull/1813#discussion_r1133927238
