### ISSUE TITLE
Deduplicate ring buffer storage logic

### ISSUE THREAD

**Issue by serban300** [paritytech/parity-bridges-common#1599]
Right now we have 2 pallets that use some sort of ring buffers logic for storage values:

[grandpa](https://github.com/paritytech/parity-bridges-common/blob/9575229d939c5f82b0e24186bcdab7f6f7d6a123/modules/grandpa/src/lib.rs#L499-L510)
[parachains](https://github.com/paritytech/parity-bridges-common/blob/9575229d939c5f82b0e24186bcdab7f6f7d6a123/modules/parachains/src/lib.rs#L544-L577)

And we'll need the same kind of logic for the soon to come [beefy](https://github.com/paritytech/parity-bridges-common/blob/f97c2c1cd6211e4466e667981945e11b86c1127f/modules/beefy/src/lib.rs#L270-L290) pallet.

It would be ideal if we could have a special storage type for this. Something like `StorageRingBuffer`. I'm not sure if this would be possible. But at least some helper logic would be nice.

**Comment by svyatonik** [comment]
Re BEEFY - please also consider an option where the BEEFY pallet is only storing single (last) commitment (or how it is called - I've forgot already :/). IIRC you may prove anything in the history just by using latest MMR hash and providing a proper proof. @acatangiu please correct me if I'm wrong

**Comment by serban300** [comment]
Good idea ! I didn't realize this. It should work and it should simplify the implementation.

**Comment by svyatonik** [comment]
There's a tradeoff between storing headers/commitments - then e.g. you may only verify MMR proof once and then only verify e.g. storage proofs. If you not gonna store headers+commitments, then you'll need to verify MMR proofs (for old headers) every time. So please don't take my comment as a requirement - just as an option. Choose the better way :)

**Comment by serban300** [comment]
Ok, got it. Not sure what's the better way right now. We'll probably discuss more on the beefy pallet PR that will follow. Maybe we'll start with the ring buffer at first and then we'll see.

Anyway, as for this issue, deduplicating the logic for the storage ring buffers is possible, but it's a bit complicated since the grandpa pallet uses StorageMap, while the parachains pallet uses StorageDouble map. We would need to create a lot of abstractions and probably it's not worth it. I will close this issue.
