### ISSUE TITLE
Relay can't detect if node is offline

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#161]
Part1: It looks like after we have migrated to shared client, we also lost ability to receive transport-related RPC errors. I.e. if you start relay with both nodes online, but then stop and start some node again, relay will hang forever, because transport errors are lost somewhere in background threads.

Part2 (depends on way how we resolve part1): if stopping node would spoil `jsonrpsee::Client` forever, we'll need to create new instance. I've started implementing that before realizing that all transport errors are lost. Intermediate results are [in this branch](https://github.com/paritytech/parity-bridges-common/tree/reconnect-on-transport-error). I'll leave it there for now.

**Comment by svyatonik** [comment]
related #281 #288

**Comment by tomusdrw** [comment]
@svyatonik is this still an issue?

**Comment by svyatonik** [comment]
Yes, the 2nd part
