### ISSUE TITLE
Rework Relay CLI

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#162]
Currently the CLI is build with `clap` and the way we handle params has imho two disadvantages:
1. There is a bunch of back-and-forth and stringifyied parameters between `cli.yml` and `main.rs`
2. We start with `default` values of all parameters and only override them if they are  provided in the CLI. Some parameters however should be mandatory (like `eth-contract` address). The defaults are configured for `--dev` chain, but to be fair I'd prefer to have them required instead of learning one-by-one which are misconfigured.

I'd suggest to rewrite the CLI to `structopt`.

**Comment by svyatonik** [comment]
(I'm currently adding another (auto) mode for tx proofs relay)

**Comment by svyatonik** [comment]
OK - it seems that I've misclicked. I'm actually working on #164 for last couple of days :/

**Comment by tomusdrw** [comment]
Closing this, cause it's only the ethereum relay now using `clap`, which is much lower priority.
