### ISSUE TITLE
Fix Statemine runtime after with-Statemint bridge pallet is ready

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1626]
See TODOs in this file: https://github.com/paritytech/parity-bridges-common/pull/1625/files#diff-2e5d0fe8d548b2e7230cf55913c88f1a1c591e16c57ba3be6fd65221cdcdcffd

**Comment by bkontur** [comment]
@svyatonik 
I guess, we dont need this issue, because we dont need conversion-rate, right?
