### ISSUE TITLE
Complex bridge hub relay

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1629]
#1565 is introducing standalone messages, GRANDPA and parachains relay. But what we'll need in our actual deployment is the complex relay. It needs to be implemented once #1565 is merged

UPD: also version guard is currently missing from the finality relays - it needs to be added

**Comment by bkontur** [comment]
complex relay means something like to join commands (loops): RelayHeaders/RelayParachains/RelayMessages to the one command (loop) ComplexRelay? 

so that we need to run just one substrate-relayer command?

**Comment by svyatonik** [comment]
Exactly. Apart from that it is decreasing costs of running relayers - i.e. standalone GRANDPA relayer will submit every header it is seeing (unless `--only-mandatory-headers` flag is passed). Standalone parachains relay will submit every updated head it sees. In complex relay messages relay is orchestrating everything - it'll say to GRANDPA and parachains relay that it needs specific relay header/parachain head at the bridged chain => most of time it is idle and transactions are only submitted when we need them

**Comment by bkontur** [comment]
@svyatonik 
perfect, that would be very cool, to have just one configurable `substrate-relay` at the end,
it will very simplify deployment and usage and other stuff

**Comment by svyatonik** [comment]
Yeah, I agree. But we also have this conversion-rate-updater at Statemine, which (I believe) will be running as a standalone process (it doesn't fit the current complex relay architecture at all :) ). Following the initial deployment, we may also want to deploy transaction resubmitters - also a separate processes, but they may be embedded into complex relay (possibly good idea to explore that too).

**Comment by bkontur** [comment]
@svyatonik 
Slava, do we need to do here anything else?
complex relay for Rococo/Wococo is done and works: https://github.com/paritytech/parity-bridges-common/issues/1662

**Comment by svyatonik** [comment]
> UPD: also version guard is currently missing from the finality relays - it needs to be added

I think this part is missing
