### ISSUE TITLE
Remove messaging code that doesn't fit our current deployment scenario

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1638]
There's a lot of code that we are still supporting, but which is not needed (and sometimes even causes some slowdowns/troubles/mistakes/misunderstandings) in our planned deployment. Everything below needs a final confirmation, which is expected yet => onice.

1. ~We are not going to accept XCM messages from end-users, hence we don't need `send_message` and `increase_message_fee` calls of the messaging pallet~ Done in #1642

2. ~Since we are not going to reward relayers initially, we don't need relayer account ID in `receive_messages_proof` and `InboundLaneData::relayers`. But we may need it in the future, so probably worth keeping it for now?~ We'll be rewarding relayers - see #1648

3. ~We are no longer interested in computing exact message fee on bridge hubs, so we don't need conversion rate, fee multipliers messaging parameters in the runtime. Also we don't need this whole estimate-fee functionality at all (requires changes in both runtime and relay).~ Done in #1642

4. ~An effect of all previous points - we don't need conversion rate updater in complex relay. We don't need a rational relay mode anymore.~ Done in #1642

Imo if we won't use this code soon (and apparently we won't), then it is better to remove it asap.

UPD: most of this is done #1642, but I'll leave it open for some time - pretty sure there are some leftovers that need to be wiped.

**Comment by svyatonik** [comment]
We no loner need `DeliveredMessages::dispatch_results`

**Comment by svyatonik** [comment]
`ESTIMATE_MESSAGE_FEE_METHOD`

**Comment by svyatonik** [comment]
`BlockWeights` from primitives - do we need it?

**Comment by svyatonik** [comment]
`WeigthToFee`? https://github.com/paritytech/parity-bridges-common/pull/1712/files#diff-8518c3485aec64d8472c504c979776c33c3cc7c5603f401db705bd5230fdf54cR86

**Comment by serban300** [comment]
@svyatonik I can check if `WeigthToFee` is used and remove it if needed. If that's ok with you.

**Comment by svyatonik** [comment]
> @svyatonik I can check if `WeigthToFee` is used and remove it if needed. If that's ok with you.

Sure, thank you! :)

**Comment by serban300** [comment]
Yes, `WeightToFee` doesn't seem to be needed. It's used in the definitions of the Millau and Rialto chains, but it's not used by the bridges. I posted #1713 for removing it.

**Comment by svyatonik** [comment]
Messages pallet owner?

**Comment by bkontur** [comment]
> Messages pallet owner?

for production-like (Kusama, Polkadot) we shouldnt use any pallet owner and for Rococo/Wococo we dont use it,
for Rilato/Millau or other use-cases I dont know

**Comment by svyatonik** [comment]
Sorry, I mean `substrate-relay` cli argument for the messages pallet owner, which has only been used to update conversion rate (iirc). The owner concept remains
