### ISSUE TITLE
CLI to relay transaction proofs

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#164]
A simple CLI tool that the user can run for themselves that will:
- [ ] Monitor transactions from address `A` to a pre-defined locking contract address `B`
- [ ] Each time the transaction is made it will construct an inclusion proof and submit it to Substrate chain (note it has to wait for the headers to be available first).
- [ ] The transaction is sent from a pre-configured (and topped up) substrate account.

In the future we might extend this to monitor multiple ETH addresses instead.
(so you can run a relayer for others)

**Comment by HCastano** [comment]
This is partially covered by #177. It's not a standalone binary, but accomplishes a similar goal.

**Comment by svyatonik** [comment]
(I'm currently adding another (auto) mode for tx proofs relay)
