### ISSUE TITLE
Fix ChainWithMessages::WeightInfo with correct values according to BridgeHub parachains

### ISSUE THREAD

**Issue by bkontur** [paritytech/parity-bridges-common#1640]
From Slava PR comment:

> WeightInfo is used to compute message delivery transaction limits. I think it is fine to use () for initial estimations (relay leaves some reserve anyway && () weights are probably larger than actual weights), but later we'll need to use weights from the parachains.

**Comment by svyatonik** [comment]
Just an idea for the future: maybe use something like this - https://github.com/ggwpez/substrate-weight-compare - and then just compare on upgrade

**Comment by bkontur** [comment]
@svyatonik 
Slava, we have finally generated weights in Cumulus:

https://github.com/paritytech/cumulus/blob/bridge-hub-rococo-wococo/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_bridge_messages_bench_runtime_with_bridge_hub_rococo_messages_instance.rs

https://github.com/paritytech/cumulus/blob/bridge-hub-rococo-wococo/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/pallet_bridge_messages_bridge_messages_bench_runtime_with_bridge_hub_wococo_messages_instance.rs

so what do you suggest? How should we fix/change this:
```
        // TODO: fix (https://github.com/paritytech/parity-bridges-common/issues/1640)
	type WeightInfo = ();
```

**Comment by svyatonik** [comment]
Just got an idea when writing an answer - weights are used to compute maximal number of messages and their dispatch weight in delivery transaction. Maybe we should just provide CLI options for "foreign" chains for that? I.e. for Rialto/Millau we'll still have auto-computations and for RBH/WBH we'll have to use cli options like `--max-messages-in-delivery-transaction 1024 --max-dispatch-weight-in-delivery-transaction "(866_600_106_667, 2_271_915)"`.

And maybe the best alternative for now is just to choose safe values for those limits and hardcode it somewhere in primitives. E.g. to call `select_delivery_transaction_limits` using RBH/WBH weights, div result by two and use it in RBH<>WBH bridge.

My first idea was that we should check/handle it in some way in this runtime-upgrade-helper-tool that we'll have somedeay I hope.
