### ISSUE TITLE
Remove MintReward and introduce PayRewardFromAccount

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1654]
Right now there's a single implementation of `PaymentProcedure` for the `pallet-bridge-relayers` - it is the `MintReward`, which just mints relayer reward. Minting is not actual anymore. Instead the reward will be paid from some account (sovereign account of the parachain at bridge hub), so having `PayRewardFromAccount` would be great

**Comment by acatangiu** [comment]
If `PayRewardFromAccount` is a runtime configurable, then the bridge uses a single (sovereign) account to pay all rewards regardless of the message `(Source, Destination)`.

This is fine for now, but in the future we might want to implement a more complex `(Source, Destination) -> PayRewardFromAccount` mapping to allow better control of which messages are paid out by whom.
