### ISSUE TITLE
Prepare complex relayer for BridgeHubRococo/BridgeHubWococo setup

### ISSUE THREAD

**Issue by bkontur** [paritytech/parity-bridges-common#1662]
- parachain to parachain kind
`impl Full2WayBridge for BridgeHubRococoBridgeHubWococoFull2WayBridge {`

**How to test locally:**
- run BridgeHubRococo/BridgeHubWococo parachains setup from cumulus with zombienet
 https://github.com/paritytech/cumulus/tree/bridge-hub-rococo-wococo/parachains/runtimes/bridge-hubs#run-chains-rococo--bridgehub-wococo--bridgehub-with-zombienet
- run relaying - here are all commands: `init-bridge` / `relay-headers` / `relay-parachains` / `relay-messages`
  https://github.com/paritytech/cumulus/tree/bridge-hub-rococo-wococo/parachains/runtimes/bridge-hubs#run-relayers-rococo-wococo

**Goal:**
- replace all commands `relay-headers` / `relay-parachains` / `relay-messages`  by one complex relayer run
  - at least check if it is possible

**Comment by serban300** [comment]
Fixed by #1663 and https://github.com/paritytech/cumulus/pull/1913 . Closing.

**Comment by bkontur** [comment]
Serban, thank you :)
