### ISSUE TITLE
[BridgeHub] Add and run Basic unit tests 

### ISSUE THREAD

**Issue by EmmanuellNorbertTulbure** [paritytech/parity-bridges-common#1672]
For Rococo - Wococo

- [ ] add integrity tests to the bridge-hub-rococo runtime (for both sides R->W and W->R)
```
     fn ensure_bridge_integrity() {
		assert_complete_bridge_types!(
```
- [ ] ...

**Comment by serban300** [comment]
Leaving the integrity test for Rialto -> Millau as an example: https://github.com/paritytech/parity-bridges-common/blob/ec6bafaf0190539644291fc544563c34619647e7/bin/rialto/runtime/src/millau_messages.rs#L206

**Comment by serban300** [comment]
Started adding integrity tests for Rococo -> Wococo and Wococo -> Rococo. There are 2 issues so far:

1. [Checking the type of the InboundPayload](https://github.com/paritytech/parity-bridges-common/blob/8649d12afb92863ed4cda1b13114315a46fa4c1a/bin/runtime-common/src/integrity.rs#L92). The tests expects a [`FromBridgedChainMessagePayload`](https://github.com/paritytech/parity-bridges-common/blob/8649d12afb92863ed4cda1b13114315a46fa4c1a/bin/runtime-common/src/messages.rs#L377), but we use [`XcmAsPlainPayload`](https://github.com/paritytech/cumulus/blob/d42acfdd35db3500cb51945b882795d1d71e1f33/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/bridge_common_config.rs#L31) for [`BridgeHubRococo` and `BridgeHubWococo`](https://github.com/paritytech/cumulus/blob/d42acfdd35db3500cb51945b882795d1d71e1f33/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs#L530) 

@bkontur @svyatonik do we plan to use `FromBridgedChainMessagePayload` here in the future ? 

2. [Checking the `BlockWeights`](https://github.com/paritytech/parity-bridges-common/blob/8649d12afb92863ed4cda1b13114315a46fa4c1a/bin/runtime-common/src/integrity.rs#L165-L172). For `BridgeHubRococo` and `BridgeHubWococo` we expect to find the weights defined in [`polkadot-core`](https://github.com/paritytech/parity-bridges-common/blob/8649d12afb92863ed4cda1b13114315a46fa4c1a/primitives/polkadot-core/src/lib.rs#L97-L114) which use the constants defined also in [`polkadot-core`](https://github.com/paritytech/parity-bridges-common/blob/8649d12afb92863ed4cda1b13114315a46fa4c1a/primitives/polkadot-core/src/lib.rs#L71-L84). But instead the runtime uses the same [formula](https://github.com/paritytech/cumulus/blob/d42acfdd35db3500cb51945b882795d1d71e1f33/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs#L229-L246), but with other constants defined in [`cumulus/parachains/common`](https://github.com/paritytech/cumulus/blob/d42acfdd35db3500cb51945b882795d1d71e1f33/parachains/common/src/lib.rs#L87-L97) and other [`BlockExecutionWeight`](https://github.com/paritytech/cumulus/blob/d42acfdd35db3500cb51945b882795d1d71e1f33/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/block_weights.rs#L26).

**Comment by serban300** [comment]
Thanks for the answer !

> My guess that we'll be using XcmAsPlainPayload. @bkontur wanted to backport his changed to the parity-bridge-common, so in the end the FromBridgedChainMessagePayload will use the same payload.

@bkontur can I help with backporting this change ? Is there an issue for it ?

> I've tried to find where we are using those BlockWeights and it seems that they are no longer required. So IMO we need to remove this check - added https://github.com/paritytech/parity-bridges-common/issues/1638#issuecomment-1344103794 to the https://github.com/paritytech/parity-bridges-common/issues/1638. It needs to be double checked before removal

Ok, I can double check this and remove the `BlockWeights` and the assert.

**Comment by serban300** [comment]
> I've tried to find where we are using those BlockWeights and it seems that they are no longer required. So IMO we need to remove this check - added https://github.com/paritytech/parity-bridges-common/issues/1638#issuecomment-1344103794 to the https://github.com/paritytech/parity-bridges-common/issues/1638. It needs to be double checked before removal

@svyatonik I checked this and we use the `BlockWeights` in computing the [`max_extrinsic_weight()`](https://github.com/paritytech/parity-bridges-common/blob/8649d12afb92863ed4cda1b13114315a46fa4c1a/primitives/polkadot-core/src/lib.rs#L341), which is then used in messages relaying [here](https://github.com/paritytech/parity-bridges-common/blob/8649d12afb92863ed4cda1b13114315a46fa4c1a/relays/lib-substrate-relay/src/messages_lane.rs#L119-L125). I guess we still need this if I understand correctly.

**Comment by svyatonik** [comment]
> > I've tried to find where we are using those BlockWeights and it seems that they are no longer required. So IMO we need to remove this check - added [#1638 (comment)](https://github.com/paritytech/parity-bridges-common/issues/1638#issuecomment-1344103794) to the #1638. It needs to be double checked before removal
> 
> @svyatonik I checked this and we use the `BlockWeights` in computing the [`max_extrinsic_weight()`](https://github.com/paritytech/parity-bridges-common/blob/8649d12afb92863ed4cda1b13114315a46fa4c1a/primitives/polkadot-core/src/lib.rs#L341), which is then used in messages relaying [here](https://github.com/paritytech/parity-bridges-common/blob/8649d12afb92863ed4cda1b13114315a46fa4c1a/relays/lib-substrate-relay/src/messages_lane.rs#L119-L125). I guess we still need this if I understand correctly.

Yeah, you're right, thank you! Then we need to change weights of our parachains Rococo/Wococo/Polkadot/Kusama bridge hubs to what Cumulus offers. Then it should be fine. Sorry for misleading you :/

**Comment by svyatonik** [comment]
> @serban300 I am waiting for one PR to be merged to the polkadot gav-xcm-v3 and after that I would like to update (polkadot/substrate) deps for parity-bridges-common + cumulus, so after that I would like to backport that
> 
> and to the weights, those block_weights in cumulus they are just copy/past from other cumulus runtimes, what is another issue, related to this weights, we need to add all bridges pallets to the automatic benchmarking here: https://github.com/paritytech/cumulus/blob/master/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs#L463-L470 to be able to regenerate weights in cumulus with bench.bot, you could take this issue, if you want: #391
> 
> ```
> e.g.:
> /cmd queue -c bench-bot $ xcm statemint assets pallet_xcm_benchmarks::fungible
> 
> /cmd queue -c bench-bot $ pallet bridge-hub-rococo bridge-hubs pallet_bridges_granda
> /cmd queue -c bench-bot $ pallet bridge-hub-rococo bridge-hubs pallet_bridges_parachain
> /cmd queue -c bench-bot $ pallet bridge-hub-rococo bridge-hubs pallet_bridges_messages
> /cmd queue -c bench-bot $ pallet bridge-hub-rococo bridge-hubs pallet_bridges_rewards
> ```

That's a bit different weights - they're weights of calls, not block limits. And we yet need to find a way to deal with these. This should probably be a part of release process (manual) - i.e. we'll be checking that weights in our repo are close to what bridge hubs are using. Let's probably not touch it now

**Comment by bkontur** [comment]
@serban300 
backport is ready, https://github.com/paritytech/parity-bridges-common/pull/1813

but I was thinking, if should better change that integrity test, to be more flexible:
https://github.com/paritytech/parity-bridges-common/blob/8649d12afb92863ed4cda1b13114315a46fa4c1a/bin/runtime-common/src/integrity.rs#L90-L92

for example `FromThisChainMessagePayload / FromBridgedChainMessagePayload<CallOf<ThisChain<$bridge>>>` could be passed as macro parameter, it will be more flexible and generic, rialto/millau stuff could still use `FromBridgedChainMessagePayload` and BridgeHubs `XcmAsPlainPayload` or whatever, wdyt?

**Comment by serban300** [comment]
I'm taking a more detailed look on the tests to see what would be the best solution

**Comment by serban300** [comment]
Resolved by https://github.com/paritytech/cumulus/pull/1975
