### ISSUE TITLE
[R-W Bridge] Build a Document (Guide/Checklist) on how to use the RW Bridge and set up the logistics needed to run it

### ISSUE THREAD

**Issue by EmmanuellNorbertTulbure** [paritytech/parity-bridges-common#1680]
- [x] Test accounts for relayer
- [x] endpoints
- [x] initialize bridge hubs
- [x] HRMP channels 

etc. If possible to create a template we can use for future bridges as well

**Comment by bkontur** [comment]
https://github.com/paritytech/parity-bridges-common/issues/1671
https://github.com/paritytech/parity-bridges-common/issues/1730
