### ISSUE TITLE
[P-K Bridge] AssetHubPolkadot->AssetHubKusama asset transfer

### ISSUE THREAD

**Issue by EmmanuellNorbertTulbure** [paritytech/parity-bridges-common#1688]
- [ ] setup relayer version-mode guard with Bundle https://github.com/paritytech/parity-bridges-common/pull/1697

Do we allow to move DOTs to Kusama, since Kusama has less security?
We need to allow to transfer KSM back to Kusama?

- Finish https://github.com/paritytech/cumulus/pull/2013

**Comment by bkontur** [comment]
Implemented by https://github.com/paritytech/cumulus/pull/2762
+ withdraw reserve will be fixed here: https://github.com/paritytech/parity-bridges-common/issues/2256
