### ISSUE TITLE
Renaming docker image

### ISSUE THREAD

**Issue by BulatSaif** [paritytech/parity-bridges-common#1708]
Naming is one of the hardest tasks.
### Current state: 
- Docker image:  [**substrate-relay**](https://hub.docker.com/r/paritytech/substrate-relay)
- Helm chart: [**parity-bridge-common**](https://github.com/paritytech/helm-charts/tree/main/charts/parity-bridge-common)
- This repository: [**parity-bridges-common**](https://github.com/paritytech/parity-bridges-common)
- Old repository: [**substrate-bridge-relay**](https://github.com/paritytech/substrate-bridge-relay)

### Confusion: 
When you see `substrate-relay` docker image you expect it came from `substrate-bridge-relay` git  repo. 
Helm chart `parity-bridge-common` can deploy only relay not all common parts, it also misses `S` in `bridgeS`

### Proposed new names:
- Docker image: parity-bridges-common-relay
- Helm chart: parity-bridges-common-relay 

### Links
docker image name is  set here: https://github.com/paritytech/parity-bridges-common/blob/45ec413fd31e22660c0b008ea1c205db8840f4b9/.gitlab-ci.yml#L299

**Comment by svyatonik** [comment]
Sorry, I've missed this issue on creation. IMO:

> When you see substrate-relay docker image you expect it came from substrate-bridge-relay git repo.

[`substrate-bridge-relay`](https://github.com/paritytech/substrate-bridge-relay) is archived, so not much confusion here. We may additionally left a link there, pointing to this repo.

> Helm chart parity-bridge-common can deploy only relay not all common parts, it also misses S in bridgeS

Other parts of this repo are either "common" at code level (pallets) or are not common at all (e.g. our ephemeral testnets). So `substrate-relay` is the only thing we actually need :) 

IMO rename would cause a wave of other changes and now it isn't a perfect time for that. Can we pause this issue, please, until we have a pause in development?

I fully agree with [this suggestion](https://github.com/paritytech/parity-bridges-common/issues/1708#issuecomment-1346260957).

**Comment by bkontur** [comment]
@BulatSaif 
totally agree with Slava, renaming repo now it is not the best time :)

I changed the docker name, you can use this now:
```
docker pull paritytech/bridges-common-relay:v2022-12-12-rowo-1
```

could you, please, also update docker name/version in that PR
https://gitlab.parity.io/parity/infrastructure/parity-testnet/-/merge_requests/694/diffs#7aef2ce78abe64e94d5ec0904832986508e663f2_0_2 ?

**Comment by bkontur** [comment]
@BulatSaif 
oh, please, wait, probably I need to fix that new image new

**Comment by BulatSaif** [comment]
Thank you @bkontur for renaming the docker image. 
I will rename the helm chart to `bridges-common-relay`

Of course, the git repo renaming can wait.
