### ISSUE TITLE
Consider using indirect runtime calls for `RialtoParachain`

### ISSUE THREAD

**Issue by serban300** [paritytech/parity-bridges-common#1745]
At the moment we use direct runtime calls for all the runtimes that are defined in this repo. The problem with this is that we don't have any way to test that the indirect runtime calls logic works within our test deployments. So for example if there is any issue with the indirect runtime logic calls we will find out only after we deploy it to rococo/wococo.

If we used the indirect call logic for one of the runtimes that are defined in this repo, we would catch many potential issues as part of our test deployments. For example I think it would be the easiest to use this for `RialtoParachain`.

Context:
By direct runtime call I'm referring to using the runtime calls defined by `construct_runtime!()`. We can do this only for the runtimes defined in our repo. For example [for rialto parachain](https://github.com/paritytech/parity-bridges-common/blob/209cba353ce09a6262f3b518011b794bc5990726/relays/client-rialto-parachain/src/lib.rs#L50). While for runtimes that are not defined in our repo we use "indirect runtime calls", which is are basically a mock of the runtime. For example [bridge hub rococo](https://github.com/paritytech/parity-bridges-common/blob/209cba353ce09a6262f3b518011b794bc5990726/relays/client-bridge-hub-rococo/src/runtime_wrapper.rs#L46).

@svyatonik do you think this would make sense ?

**Comment by svyatonik** [comment]
Yeah - we may do that. But imo for external runtimes we'll need some more sophisticated testing - there's a lot that can break and we won't be able to detect that by only testing it on `RialtoParachain` - e.g. pallet index, call change, upgrading only one side of the bridge, ... So probably we'll need some tool (can we use zombienet for that?) that will spin up (local) upgraded chains and will start required relayers and will say us that everything went smoothly.

But in any case - having it on `RialtoParachain` sounds good to me.
