### ISSUE TITLE
Send message through the bridge at least once per day

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1840]
We have on-chain pallets. We have relay. We have monitoring stuff that gives us alerts if we are unable to deliver queued messages, relay headers, ... But what if noone sends any messages + we keep syncing mandatory relay chain headers, but actually something has broken in our bridge?

The suggestion is to send messages through the bridge (ideally in both directions), then if they are stuck, our monitoring shall detect that and give use alerts.

**Comment by EmmanuellNorbertTulbure** [comment]
@bkontur to send script to @svyatonik

**Comment by bkontur** [comment]
https://github.com/paritytech/devops/issues/2356

`send_xcm_transact_remark_from_statemine` or `send_xcm_trap_from_statemine`
https://github.com/paritytech/cumulus/blob/bridge-hub-rococo-wococo/scripts/bridges_rococo_wococo.sh#L78

**Comment by svyatonik** [comment]
PR that will hopefully fix the missing files error:
https://gitlab.parity.io/parity/infrastructure/parity-testnet/-/merge_requests/941

So we just need to wait and check the logs to see if it works

**Comment by svyatonik** [comment]
Message from RBH to WBH is now sent every 6 hours. I've added an alert that should fire if there are no messages sent over last 24 hours, but it shows "No data" on our Grafana and I have no idea - why :confused: I'm gonna close this issue for now and track the alert separately. In any case - if messages will be sent, but not delivered, we shall see our regular errors
