### ISSUE TITLE
Deduplicate signed extensions

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1896]
Origin: https://github.com/paritytech/parity-bridges-common/pull/1894#discussion_r1111971768

- [x] There are now several signed extensions in `bp-polkadot-core` crate. We are not going to submit transactions to any polkadot-like (i,e. relay) chains, so le'ts probably move this stuff to the `bp-bridge-hub-cumulus` crate?
- [ ] check `check_additional_signed` if we need or not for cumulus, because it does not work for BridgeHubRooco/Wococo with:
```
	// for relayer
        type RewardingBridgeSignedExtra = (
		CheckNonZeroSender,
		CheckSpecVersion,
		CheckTxVersion,
		CheckGenesis<PolkadotLike>,
		CheckEra<PolkadotLike>,
		CheckNonce<Nonce>,
		CheckWeight,
		ChargeTransactionPayment<PolkadotLike>,
		BridgeRejectObsoleteHeadersAndMessages,
		RefundBridgedParachainMessagesSchema,  // <= placeholder
	);
	
	vs.
	
	// runtime definition
	pub type SignedExtra = (
		frame_system::CheckNonZeroSender<Runtime>,
		frame_system::CheckSpecVersion<Runtime>,
		frame_system::CheckTxVersion<Runtime>,
		frame_system::CheckGenesis<Runtime>,
		frame_system::CheckEra<Runtime>,
		frame_system::CheckNonce<Runtime>,
		frame_system::CheckWeight<Runtime>,
		pallet_transaction_payment::ChargeTransactionPayment<Runtime>,
		BridgeRejectObsoleteHeadersAndMessages,
		(BridgeRefundBridgeHubRococoMessages, BridgeRefundBridgeHubWococoMessages), // ((), ())
	);
```

**Comment by bkontur** [comment]
for

**Comment by bkontur** [comment]
when it goes about `bp-bridge-hub-cumulus` (Cumulus primitives), probably that SignedExtension  (`pub mod rewarding_bridge_signed_extension`) could be maybe placed somewhere to relayer layer, because it is not used in runtime (just in test), see more [here](https://github.com/paritytech/parity-bridges-common/pull/1894#discussion_r1113627207)

**Comment by svyatonik** [comment]
So I was playing with reflection for couple of hours and it looks ugly. Let's probably live without that `check_additional_signed`. I mean - we already have this code in RBH/WBH:
```rust
		let payload: SignedExtra = (
			frame_system::CheckNonZeroSender::new(),
			frame_system::CheckSpecVersion::new(),
			frame_system::CheckTxVersion::new(),
			frame_system::CheckGenesis::new(),
			frame_system::CheckEra::from(sp_runtime::generic::Era::Immortal),
			frame_system::CheckNonce::from(10),
			frame_system::CheckWeight::new(),
			pallet_transaction_payment::ChargeTransactionPayment::from(10),
			BridgeRejectObsoleteHeadersAndMessages {},
			(
				BridgeRefundBridgeHubRococoMessages::default(),
				BridgeRefundBridgeHubWococoMessages::default(),
			),
		);

		let bhr_indirect_payload =
			bp_bridge_hub_rococo::rewarding_bridge_signed_extension::from_params(
				10,
				10,
				TransactionEra::Immortal,
				test_header::<bridge_hub_test_utils::RelayBlockHeader>(1).hash(),
				10,
				10,
			);
		assert_eq!(payload.encode(), bhr_indirect_payload.encode());
```

So if we are changing the `SignedExtra` type (e.g. by adding new `u32` field), we will also fix the `bp_bridge_hub_rococo::rewarding_bridge_signed_extension` to pass the test. And if we are just adding the unit, we may not update the code (at least it was ignored by my reflection-based code). Feel free to reopen if you still think we need it
