### ISSUE TITLE
Confirmation race stalls sometimes

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#1901]
https://github.com/paritytech/parity-bridges-common/pull/1898#issuecomment-1440295257

The relay is able to recover after some time (at least it is how it was resolved for me locally), but looks like it is an actual issue (3+ minutes confirmation delays). It maybe related to #1898, or maybe it was there before?

**Comment by serban300** [comment]
Thanks for investigating this !

It also reproduces on the test deployments. For example here is an almost 10min delay:

![image](https://user-images.githubusercontent.com/18124062/220841954-797e5ab2-d274-4b7b-b7da-ec83321d0e62.png)

Dashboard link: https://grafana.rialto.brucke.link/d/-l61a7r7k/rialtoparachain-to-millau-message-sync-dashboard?orgId=1&from=1677135720000&to=1677136380000

The delay is only in message confirmations. I haven't seen any stall in grandpa finality. Probably the stall that I was experiencing yesterday locally was related to something else.

**Comment by svyatonik** [comment]
Yeah, thank you! I already know what's happening and currently thinking whether we need to fix it (it isn't actually a code bug - just our design and how we use bridge on our test deployments) or it is fine to leave it as is
