### ISSUE TITLE
FATAL: Unable to initialize the API: createType(BlockHash):: Expected input with 32 bytes (256 bits), found 64 bytes

### ISSUE THREAD

**Issue by arunjot12** [paritytech/parity-bridges-common#1905]
I was running parity-bridges-common but the second node explorer is showing this error. Please guide me through this. enter image description here

![Screenshot from 2023-02-24 12-41-40](https://user-images.githubusercontent.com/101393963/221123712-49dacb97-6b42-4a64-bf0c-3519bb7c3ef8.png)

**Comment by svyatonik** [comment]
We're using custom 512-bit hasher for Millau testnet and it isn't supported by js apps, unfortunately. There's no way now to configure it

**Comment by svyatonik** [comment]
Fore reference: https://github.com/polkadot-js/apps/issues/8418
