### ISSUE TITLE
XCM ExportMessage command weight 

### ISSUE THREAD

**Issue by EmmanuellNorbertTulbure** [paritytech/parity-bridges-common#1943]
How to calculate the weight of message instruction on BridgeHub.

**Comment by acatangiu** [comment]
Should be fixed by https://github.com/paritytech/polkadot/pull/6923 and https://github.com/paritytech/cumulus/pull/2353

**Comment by acatangiu** [comment]
fixed by https://github.com/paritytech/polkadot/pull/6923 and https://github.com/paritytech/cumulus/pull/2353
