### ISSUE TITLE
Use host functions for proof verification once available

### ISSUE THREAD

**Issue by acatangiu** [paritytech/parity-bridges-common#1950]
Depending on discussion here https://github.com/paritytech/srlabs_findings/issues/280

**Comment by serban300** [comment]
@acatangiu is this issue still actual ? I see that the mentioned issue was resolved. And we seem to have the dependencies mentioned there.

**Comment by acatangiu** [comment]
I honestly don't remember the full context here - we all discussed this in the team retreat and I quickly opened this issue but obviously didn't provide enough context for our future selves :see_no_evil: 

@svyatonik do you remember the details here?

**Comment by svyatonik** [comment]
Let's check if the updated code is actually used by us when we check storage proofs (may also be related to this optimization stuff you're working now on, @serban300 ). If we use it, let's close

**Comment by serban300** [comment]
Ok, will check after doing the optimization

**Comment by serban300** [comment]
Checked. The updated code only touches the Memory and Trie DBs. We also use the recorder which was not updated. 

But if we switch all proofs to the new `VecDb`, I think we should be ok. I should check if we use the Recorder in other places, but I suppose not. For the moment, the currently opened PR, only switches the messages delivery proofs: #2155 . If this works ok and the feedback is positive, I'll switch the other proofs to use the `VecDb`.

**Comment by serban300** [comment]
Fixed by #2194
