### ISSUE TITLE
Why target-signer account balance is deducted in parity-bridges-common?

### ISSUE THREAD

**Issue by Amit22antier** [paritytech/parity-bridges-common#2049]
Hi I'm sending a message from millau-rialto in the encoded-calls-messaging bridge in which giving recipient and amount in the command. But the problem the source signer is only giving transaction fee and the target signer on another chain is paying the amount. Can someone please help me through this

```
./target/debug/substrate-relay send-message millau-to-rialto \
            --source-host localhost \
            --source-port $MILLAU_PORT \
            --source-signer //Alice\
            --target-signer //Eve \
            --lane 00000000 \
            --origin Target \
            transfer \
            --amount 10000000000000 \
            --recipient 5qTnmq6AGPoZVr29wDsgXhoLhpp3sCukSFXh7zGSaQtgCa1U \
```

**Comment by svyatonik** [comment]
Can you, please, write what you're expecting? The command above shall use accounts as:
- at Millau chain, the `//Alice` pays the full message delivery and dispatch fee in `MLAU` tokens;
- at Rialto chain, the transfer from `//Eve` to `5qTnmq6AGPoZVr29wDsgXhoLhpp3sCukSFXh7zGSaQtgCa1U` will be dispatched.

**Comment by Amit22antier** [comment]
I want that the balance that is transfered from target-signer to receipent should be deducted from source-signer, which is not getting deducted from source-signer but  getting deducted from target-signer only.

**Comment by svyatonik** [comment]
That's not how it works. They (source signer and target signer) live at different chains, so their balance is measured in different tokens. You're doing transfer of `10000000000000` `RLTO` tokens at Rialto. How many `MLAU` tokens you want to deduct from the `//Alice` account and where they should go in this case?

The target signer account is assumed to be controlled by the single entity (so in some sense source signer == target signer). I.e. you need to provide two signatures when you're sending message using the `--origin Target`: the transaction must be signed by the `source-signer` and you should prove that you have the private key for the `target-signer` && sign some additional message payload.

**Comment by svyatonik** [comment]
Please reopen if you have any other questions

**Comment by arunjot12** [comment]
No. The Source Signer should also pay the fees. Why it is only paying transaction fee?

**Comment by serban300** [comment]
I'm not sure if I understand the question. Sorry if I'm missing something. What is the encoded-calls-messaging bridge ?

For me the command that you mentioned doesn't work:

```
error: Found argument '--target-signer' which wasn't expected, or isn't valid in this context
```

And seems expected. The `send-message` command doesn't accept some of the arguments above. It only accepts:
```
pub struct SendMessage {
	/// A bridge instance to encode call for.
	#[structopt(possible_values = FullBridge::VARIANTS, case_insensitive = true)]
	bridge: FullBridge,
	#[structopt(flatten)]
	source: SourceConnectionParams,
	#[structopt(flatten)]
	source_sign: SourceSigningParams,
	/// Message type.
	#[structopt(subcommand)]
	message: crate::cli::encode_message::Message,
}
```
As defined here: https://github.com/paritytech/parity-bridges-common/blob/2a66aa32486a5a9dd90a25dd84e4b5507bd3fb6e/relays/bin-substrate/src/cli/send_message.rs#L48
