### ISSUE TITLE
Add test cases to Cumulus which simulates real e2e message delivery

### ISSUE THREAD

**Issue by bkontur** [paritytech/parity-bridges-common#2078]
Pseudocode:
```rust
fn bridge_hub_rococo_dispatch_works() {
	<initialize-externalities>::execute_with(|| {	
		let bridge_message = BridgeMessage {
			universal_dest: V3(X2(GlobalConsensus(...), Parachain(1234))),
			xcm: Xcm(...)
		};

		assert_ok!(pallet_bridge_grandpa::Pallet::<Runtime, BridgeGrandpaWococoInstance>::submit_finality_proof(...));
		assert_ok!(pallet_bridge_parachains::Pallet::<Runtime, BridgeParachainWococoInstance>::submit_parachain_heads(...));
		assert_ok!(pallet_bridge_messages::Pallet::<Runtime, WithBridgeHubWococoMessagesInstance>::receive_messages_proof(..., bridge_message, ...));
		
		// get message from `XcmpQueue::take_outbound_messages` for 1234
		let dispatched_xcm = RuntimeHelper::<HrmpChannelSource>::take_xcm(1234);
		asset_eq!(xcm, dispatched_xcm);
	})
}
````

- [ ] I will prepare everything around, but will need help with `submit_finality_proof/submit_parachain_heads/receive_messages_proof` proofs (lots of this helper code is in benchmarking stuff e.g.: `prepare_messages_storage_proof` ...)
- [ ]  add test for DeliveryConfirmationPayments when receive_messages_delivery_proof
- [ ] check economics in tests (hit delivery rewards constants)
   ```
   pub storage DeliveryRewardInBalance: u64 = 1_000_000;
   pub storage RequiredStakeForStakeAndSlash: Balance = 1_000_000;
   ```

**Comment by acatangiu** [comment]
AFAICT, [receive_single_message_proof_with_dispatch](https://github.com/paritytech/cumulus/blob/4156016d903bd2ab1af4c83f0d18e24bc01dc0be/bridges/modules/messages/src/benchmarking.rs#L414-L439) benchmark implements and verifies this e2e message delivery:

- starts with messages 1..=20 already delivered
- [opens HRMP channel to para 42](https://github.com/paritytech/cumulus/blob/6612cae69215a07e1f771ce6b0e777d2b215101c/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs#L1018)
- sets [expected message destination](https://github.com/paritytech/cumulus/blob/6612cae69215a07e1f771ce6b0e777d2b215101c/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs#L1023) to `X2(GlobalConsensus(<parent-relay>), Parachain(42))`
- [prepares inbound xcm message](https://github.com/paritytech/cumulus/blob/b0ac4fe0fa90f9a289aea9688fdd63da570ca664/bridges/bin/runtime-common/src/messages_benchmarking.rs#L61-L74) (consisting of multiple `ClearOrigin` instructions),
- [builds `FromBridgedChainMessagesProof`](https://github.com/paritytech/cumulus/blob/b0ac4fe0fa90f9a289aea9688fdd63da570ca664/bridges/bin/runtime-common/src/messages_benchmarking.rs#L139-L162) containing message above with nonce `21`
- [calls `receive_messages_proof()`](https://github.com/paritytech/cumulus/blob/4156016d903bd2ab1af4c83f0d18e24bc01dc0be/bridges/modules/messages/src/benchmarking.rs#L432) with above proof as if submitted by relayer
- [verifies `InboundLanes::<bla>::last_delivered_nonce() == 21`](https://github.com/paritytech/cumulus/blob/4156016d903bd2ab1af4c83f0d18e24bc01dc0be/bridges/modules/messages/src/benchmarking.rs#L434-L437)
- [verifies `XcmpQueue::outbound_messages` has new xcm message](https://github.com/paritytech/cumulus/blob/6612cae69215a07e1f771ce6b0e777d2b215101c/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/lib.rs#L1038) (dispatch successful)

It doesn't explicitly verify that the final `XcmpQueue::take_outbound_messages()` equals the original  `xcm` payload (`vec![ClearOrigin; n]`), but we can enhance it to do that too as a nice to have.

**Comment by acatangiu** [comment]
But above only verifies dispatch not complete flow. We want a runtime test that fully verifies side-effects of a relayer submitting `batch(grandpa_finality, parachain_heads, message_proof)`, including relayer slash/reward.
