### ISSUE TITLE
[Question] where does the fund of the `rewards_account` comes from?

### ISSUE THREAD

**Issue by boundless-forest** [paritytech/parity-bridges-common#2113]
```rs
pub struct PayRewardFromAccount<T, Relayer>(PhantomData<(T, Relayer)>);

impl<T, Relayer> PayRewardFromAccount<T, Relayer>
where
	Relayer: Decode + Encode,
{
	/// Return account that pays rewards based on the provided parameters.
	pub fn rewards_account(params: RewardsAccountParams) -> Relayer {
		params.into_sub_account_truncating(b"rewards-account")  // here
	}
}
```

There was a `relayer_acount` which was very similar to the `rewards_account` in the latest version.  The user pays the cross-chain message fee to the relayer account when sending a message, after the message delivery proof is submitted to the source chain, this account pays the rewards to the message relayer and the confirmation relayer. 

In the current code, I find that the repayer pallet are responsible for paying rewards with the `rewards_account`, this is the same with previous version. but I did not find where the fund of this account comes from. I guess the cross-chain fee might could be charged in the XCM layer or executor. If so, the `rewards_account` should be injected or configured in somewhere at runtime, but I have not found it.

**Comment by acatangiu** [comment]
Relayer rewards are paid from sovereign accounts (on source BH) of source/origin parachain. You can find more details at [Who is Rewarding Relayers](https://github.com/paritytech/parity-bridges-common/blob/master/docs/polkadot-kusama-bridge-overview.md#who-is-rewarding-relayers).

Our current plan for user fees is to have them disconnected from relayer rewards. Ongoing discussion here https://github.com/paritytech/parity-bridges-common/issues/2006.

**Comment by boundless-forest** [comment]
> Relayer rewards are paid from sovereign accounts (on source BH) of source/origin parachain.

**Comment by acatangiu** [comment]
The "rewards_account" for relayers servicing `ParaA->ParaB` lane _is_ the sovereign account of `ParaA` on `BridgeHubA`.

E.g. for `Statemint->Statemine` XCM message: `Statemint` will hold and fund sovereign accounts on `BHP` and `BHK`.

```
Statemint ---xcm(ExportMessage(inner_xcm))--> BridgeHubPolkadot ---relay(inner_xcm)--> BridgeHubKusama ---xcmp_dispatch(inner_xcm)--> Statemine
^                                             ^                                                   ^ 
|                                             |                                                   | 
user pays fee on extrinsic here,              |                                                   |
fee goes to Statemint treasury                |                                                   relayer gets "KSM tx fees refund" here for submit_message_proof()
                                              |                                                   from StatemintSovereignAccountOnBHK
                                              relayer gets "DOT tx fees refund" + "DOT reward"
                                              for submit_message_delivery_proof()
                                              from StatemintSovereignAccountOnBHP

Statemint treasury will periodically fund StatemintSovereignAccountOnBHP and StatemintSovereignAccountOnBHK
```
