### ISSUE TITLE
XCM dispatcher

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#214]
Intepret the payload of a message as XCM: https://github.com/paritytech/xcm-format and then dispatch to the right pallets.

**Comment by tomusdrw** [comment]
See: https://github.com/paritytech/polkadot/blob/e1a5c6b66f31166127b19af1fea95fd6aa833589/xcm/xcm-executor/src/lib.rs#L35

**Comment by svyatonik** [comment]
This is started in #1379, but it is far from the production-ready code

**Comment by svyatonik** [comment]
Should be done now
