### ISSUE TITLE
Improve `receive_messages_proof` benchmarks accuracy

### ISSUE THREAD

**Issue by serban300** [paritytech/parity-bridges-common#2165]
Right now we estimate the weight of `receive_messages_proof` roughly with the following formula: call weight = NumberOfMessages * (WeightOfTwoMessages - WeightOfOneMessage)

This formula seems to lose accuracy as the actual number of received messages increases. More details [here](https://github.com/paritytech/parity-bridges-common/pull/2155#issuecomment-1566697426).

We should investigate if we can improve the per message accuracy

**Comment by serban300** [comment]
I've been doing some experiments.

If we introduce another benchmark (let's say `receive_n_messages_proof`) similar to `receive_single_message_proof` but which runs on the range 1..MaxUnconfirmedMessagesAtInboundLane we get much more consistent results and the improvement brought by compact proofs is visible. 

But if we do this, `receive_single_message_proof_with_outbound_lane_state`, `receive_single_message_proof_1_kb`, `receive_single_message_proof_16_kb`, `receive_single_message_proof_with_dispatch` are not really compatible anymore. In order to make them compatible we would have to run them on 1..MaxUnconfirmedMessagesAtInboundLane as well, but that would take a lot of time.

Still thinking of a solution that would output consistent results in a reasonable time.

**Comment by acatangiu** [comment]
What does "a lot of time" mean? Benchmarking doesn't happen very often and I think everybody is fine with compromising benchmarking speed over weight accuracy.

If it doesn't take ridiculously long, and we don't have a better alternative, I think it's ok with what you have now.

@svyatonik wdyt?

**Comment by serban300** [comment]
> What does "a lot of time" mean? Benchmarking doesn't happen very often and I think everybody is fine with compromising benchmarking speed over weight accuracy.

On my machine 2-3 minutes for `receive_n_messages_proof`, 2-3 minutes for `receive_n_messages_proof_with_outbound_lane_state` and probably a bit more for `receive_n_message_proof_with_dispatch`.

For `receive_single_message_proof_1_kb` and `receive_single_message_proof_16_kb` I think we can keep them as they are.

**Comment by svyatonik** [comment]
We have had benchmarks which have been running for ~40 minutes and (imo) it is too much even for those rare cases. If they're running for couple of minutes, then it should be fine.

---

Re the weight formula change - it is a very delicate topic. I'll be super glad if we can make it easier, but imo the proof has many dimensions which affect the final weight, so it isn't trivial.

Going the easiest way (not changing the formula, but adapting it instead) - as @serban300 said, we have now `3` "main" benchmarks which may need to be updated. It is `receive_single_message_proof`, `receive_two_messages_proof` and kinda-external `receive_single_message_proof_with_dispatch`.

IIUC the `proof-verification-weight(messages-count)` dependency is now not linear - i.e. `proof-verification-weight(2) / 2` will be (much?) larger than the `proof-verification-weight(100) / 100`. The problem is that our benchmarks are building linear model, which would mean that if we simply replace the `receive_single_message_proof` + `receive_two_messages_proof` with single `receive_messages_proof(1..=1024)`, it may return smaller-than-actual weight for transactions with small number of messages. I'd start with looking at the difference - if it is actually small, then we may ignore it and try to use the single benchmark. If not, then maybe have benchmarks with some buckets - i.e. let `receive_messages_proof` has two parameters - one `messages-count // 32` and `messages-count` - then imo computed weights will be closer to the actual

**Comment by svyatonik** [comment]
> On my machine 2-3 minutes for `receive_n_messages_proof`, 2-3 minutes for `receive_n_messages_proof_with_outbound_lane_state` and probably a bit more (4-5 minutes) for `receive_n_message_proof_with_dispatch`.

If that's the only problem - then imo it is fine :)

**Comment by serban300** [comment]
> > On my machine 2-3 minutes for `receive_n_messages_proof`, 2-3 minutes for `receive_n_messages_proof_with_outbound_lane_state` and probably a bit more (4-5 minutes) for `receive_n_message_proof_with_dispatch`.
> 
> If that's the only problem - then imo it is fine :)

It suppose it will take longer on the actual machine that will run the benchmarks. And not sure if we'll need to do the same for message confirmations. In which case I'm afraid it will add up and will lead to big times. 

> I'd start with looking at the difference - if it is actually small, then we may ignore it and try to use the single benchmark. If not, then maybe have benchmarks with some buckets - i.e. let `receive_messages_proof` has two parameters - one `messages-count // 32` and `messages-count` - then imo computed weights will be closer to the actual

Will do this and come back with some numbers.

**Comment by serban300** [comment]
Ran `receive_messages_proof` with different values. The results:

Current computed message weight using `receive_single_message_proof` and `receive_two_messages_proof` =~ 12.2 mil.

50 message => weight =~ 8.5 mil per message:
```
		Weight::from_parts(424_034_000, 52645)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
```

100 message => weight =~ 8.5 mil per message:
```
		Weight::from_parts(850_156_000, 52645)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
```

250 message => weight =~ 8 mil per message:
```
		Weight::from_parts(1_959_484_000, 52645)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
```

500 message => weight =~ 7.6 mil per message:
```
		Weight::from_parts(3_816_240_000, 52645)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
```

1000 messages => weight =~ 7.6 mil per message:
```
		// Minimum execution time: 7_409_414 nanoseconds.
		Weight::from_parts(7_692_283_000, 52645)
			.saturating_add(T::DbWeight::get().reads(3_u64))
			.saturating_add(T::DbWeight::get().writes(1_u64))
```

So the difference between our value and the one for 50 messages is significant. And then between 50 and 1000 the differences are not that big.

**Comment by svyatonik** [comment]
It looks like linear to me - that is cool. I was wrong actually - I was expecting that the weight per message will grow slower than the number of messages. Let's probably just use `receive_messages_proof()` benchmark then? WDYT?

**Comment by serban300** [comment]
> Let's probably just use `receive_messages_proof()` benchmark then?

Sorry, you mean to use a single bucket ? Or a small interval ?

**Comment by svyatonik** [comment]
I mean that maybe we can replace this two things:
```rust
		let transaction_overhead = Self::receive_messages_proof_overhead();
...
		let messages_delivery_weight =
			Self::receive_messages_proof_messages_overhead(MessageNonce::from(messages_count));
...
		transaction_overhead
			.saturating_add(messages_delivery_weight)
```

With single `let base_weight = receive_messages_proof(MessageNonce::from(messages_count));`. And this `receive_messages_proof` will be a benchmark which will have single parameter `m` in range `1..=T::MaxUnconfirmedMessagesAtInboundLane::get()` - it'll just measure the weight of `receive_messages_proof` with given number of messages (and minimal proof size). All other benchmarks/weight components will probably stay the same? I may be missing something - so don't treat this as an absolute truth :) That's merely an opinion (given result of benchmarks).

**Comment by svyatonik** [comment]
Then maybe add `m` parameter to `receive_single_message_proof_with_outbound_lane_state` as well?

**Comment by serban300** [comment]
Yes, that should work

**Comment by serban300** [comment]
Actually keeping the `receive_single_message_proof` should solve this. Since by doing `receive_single_message_proof_with_outbound_lane_state` - `receive_single_message_proof` we get much more consistent results for the outbound_lane overhead. The same for the dispatch overhead. And combined with `receive_messages_proof` that you suggested above we should get both good per message accuracy and decent running time for the benchmarks.
