### ISSUE TITLE
Substrate-dispatch Transactions Generator

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#219]
Write a tool to randomly dispatch some messages to be delivered over the bridge. Should be running on both persistent and ephemeral Millau (and Westend see #218 ) to make sure the bridge is operational.

**Comment by svyatonik** [comment]
I'm going to add subcommand to our substrate relay that will submit `Call(system::remark)` message. This would allow us to test messages pallet and relay. If later we'll add separate balances module for wrapped rialto/millau, it may be extended to support these calls.

**Comment by svyatonik** [comment]
The subcommand is added (`submit-millau-to-rialto-message`), so I'm unassigning myself from this task.

**Comment by tomusdrw** [comment]
Implemented already.
