### ISSUE TITLE
Bridge Release Marketing 

### ISSUE THREAD

**Issue by EmmanuellNorbertTulbure** [paritytech/parity-bridges-common#2385]
- [x] Answer all Marcomms questions
- [x] Confirm future task list with Marcomms
- [ ] Prepare Release announcement
- [ ] Keep at least 1 Blog post a month with updates
- [ ] Bridges Article
- [ ] Create a list of all forums and places to follow post launch + feedback process
- [ ] Create post with Bridge Use case demonstration
- [ ] Create Video presentation on Bridge Use Case

**Comment by acatangiu** [comment]
https://forum.polkadot.network/t/polkadot-kusama-bridge/2971

https://www.parity.io/blog/trustless-interoperability
