### ISSUE TITLE
Tests for on-demand relays

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#2413]
Follow up for paritytech/parity-bridges-common#2129 and paritytech/parity-bridges-common#2135. Let's start implementing new `TestingClient` and add missing tests for on-demand relays (parachain and headers).

**Comment by EmmanuellNorbertTulbure** [comment]
@svyatonik to re-check and continue if needed

**Comment by svyatonik** [comment]
superseded by #3002
