### ISSUE TITLE
[P-K Bridge] Find out where to deploy relayers and who will run them.

### ISSUE THREAD

**Issue by EmmanuellNorbertTulbure** [paritytech/parity-bridges-common#2418]
Find out where to deploy relayers and who will run them. Start by discussing with Adrian/Slava.
Is the same setup like Rococo <> Wococo? Are there any special requirements?

**Comment by svyatonik** [comment]
Done. Bridge and relayer is launched. Soon (after we'll deploy latest changes to Polkadot and Kusama) we'll update the https://github.com/paritytech/polkadot-sdk/blob/master/bridges/docs/running-relayer.md with detailed instructions on how to run your own Polkadot <> Kusama relayer
