### ISSUE TITLE
[P-K Bridge] Add monitoring + alarms for BHP<>BHK

### ISSUE THREAD

**Issue by EmmanuellNorbertTulbure** [paritytech/parity-bridges-common#2419]
- [x] https://github.com/paritytech/parity-bridges-common/issues/2199

Need to adjust metrics specifically for Polkadot<> Kusama

**Comment by bkontur** [comment]
@svyatonik do you want to take? I could take a look next week

**Comment by svyatonik** [comment]
> @svyatonik do you want to take? I could take a look next week

I was planning to do that, because it is a bummer that we have it for test bridge and not for prod bridge :) But I'll probably won't have much time for that next week :/ Let's sync here - when one of us start work on that, let's just leave here a comment

**Comment by svyatonik** [comment]
@bkontur I'm picking it - will try to finish today
