### ISSUE TITLE
XCM export_message() report errors back to statemine (to release blocked funds)

### ISSUE THREAD

**Issue by EmmanuellNorbertTulbure** [paritytech/parity-bridges-common#2443]
To recover from bridge errors.

**Comment by EmmanuellNorbertTulbure** [comment]
@serban300 document the conclusion

**Comment by serban300** [comment]
The conclusion is the one above: https://github.com/paritytech/parity-bridges-common/issues/2443#issuecomment-1692857792

Closing the issue
