### ISSUE TITLE
Replace "Wococo" with "Wococo PoS"

### ISSUE THREAD

**Issue by bkontur** [paritytech/parity-bridges-common#2466]
from Versi DevOps:

> The plans changed a bit, we will not replace wococo, we deployed a new separate testnet "Wococo PoS", please feel free to use it for BridgeHub. After you finish work on the old wococo (PoA) please notify us, and we will remove it.

once Rococo <> Wococo will work, we could switch

**Hints:**
- [ ] search for `// TODO: remove this and use common from cumulus-like once fixed (https://github.com/paritytech/parity-bridges-common/issues/2466)`
- [ ] ...

**Comment by EmmanuellNorbertTulbure** [comment]
Re-check when we migrate to AssetHub Wococo

**Comment by serban300** [comment]
@bkontur since we want to use Rococo<>Westend for testing, could we close this issue ?

**Comment by bkontur** [comment]
good point :)
