### ISSUE TITLE
Check Fee on destination chain (Kusama) if it's ok

### ISSUE THREAD

**Issue by EmmanuellNorbertTulbure** [paritytech/parity-bridges-common#2561]
Running the asset transfer with both 3 and 30 DOT value, the fees on destination chain were the exact same both times, almost 1.5 DOT. Does it make sense to be this big for 3 DOTs? Is it ok?

**Comment by EmmanuellNorbertTulbure** [comment]
Yes

**Comment by bkontur** [comment]
this is probably my fault for local run,
I set minBalance: `1,000,000,000` for wDOT instead of 100,000,000,
doing testing now and after that I will close this



![image](https://github.com/paritytech/parity-bridges-common/assets/8159517/d9c43940-6dd7-449d-9742-3c05a8efbc59)

**Comment by bkontur** [comment]
Yes, that wrong min_balance for wDOTs was the problem.

Actual status for moving **DOTs** from AssetHub**Polkadot** to AssetHub**Kusama**'s Alice:

| transferred DOTs | Alice receives wDOTs | fees in wDOTS |
| --- | --- | --- |
| 3,000,000,000 (0.3 DOT) | 2,851,100,000 (cca 0.285 DOT) | 148,900,000 (cca 0.015 DOT) |
| 300,000,000,000 (30 DOT) | 299,851,100,000 (cca 29.985 DOT) | 148,900,000 (cca 0.015 DOT) |

Anyway, we read it wrong before, it was not 1.5 DOT but 0.15 DOT :)

**Comment by bkontur** [comment]
Actual status for moving **KSMs** from AssetHub**Kusama** to AssetHub**Polkadot**'s Alice:

| transferred KSMs | Alice receives wKSMs | fees in wKSMs |
| --- | --- | --- |
| 2,500,000,000,000 (2.5 KSM) | 2,490,000,000,000 (cca 2.49 KSM) | 10,000,000,000 (cca 0.01 KSM) |

**Comment by bkontur** [comment]
closing for now, everything seems ok
