### ISSUE TITLE
Investigate beefy justifications subscription error

### ISSUE THREAD

**Issue by serban300** [paritytech/parity-bridges-common#2628]
Investigate the error in this thread: https://substrate.stackexchange.com/questions/10107/beefy-justification-subscription-is-not-working

The sample code can be ran at: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/js

**Comment by serban300** [comment]
It's because `polkadot-js/api` uses `SignedCommitment` as the type for `beefy::subscribeJustifications()`. Submitted a PR for fixing this: https://github.com/polkadot-js/api/pull/5740

**Comment by iStrike7** [comment]
The issue persists with the latest polkadot api beta release `"@polkadot/api": "^8.14.2-12"`
```
DRR: createType(BeefySignedCommitment):: decodeU8a: failed at 0x01046d6880a430184b7172679dd2cb91… on commitment (index 0/2): {"payload":"BeefyPayload","blockNumber":"BlockNumber","validatorSetId":"ValidatorSetId"}:: decodeU8a: failed at 0x01046d6880a430184b7172679dd2cb91… on payload (index 0/3): Vec<(BeefyPayloadId,Bytes)>:: decodeU8a: failed at 0xbe1473009332000000000000387edaf5… (index 1/256): (BeefyPayloadId,Bytes):: decodeU8a: failed at 0x73009332000000000000387edaf5f85f… (index 1/2): Bytes:: Compact input is > Number.MAX_SAFE_INTEGER
```

**Comment by serban300** [comment]
@iStrike7  Looking at the error, it's still trying to use the old `BeefySignedCommitment` instead of `BeefyVersionedFinalityProof`. Are you sure that this version includes the fix ?

Sorry, actually the fix is in the `@polkadot/types` package, not in `@polkadot/api`. I see that the latest stable release for `@polkadot/types` is `10.10.1` and it was published 5 days ago so it doesn't contain the change: https://www.npmjs.com/package/@polkadot/types. But anyway, where can I find this beta release ("@polkadot/api": "^8.14.2-12") ? For `@polkadot/api` the latest version that I can find is also `10.10.1`.

**Comment by iStrike7** [comment]
Alright. I'll try compiling it from the source for the entire polkadot-js/api package (Since I need this for a subscription I would need the whole api package not just the types package).
Is there any guide or reference that you'd recommend to build this and link it to my local js/ts app?

**Comment by serban300** [comment]
Sorry, I am not familiar with the node packages and ecosystem. I don't know if there is any guide.

Personally this is what I did to test the changes:
- cloned the `polkadot-js/api` github project locally, ran `yarn install` and `yarn build`
- cloned the `polkadot-js/apps` github project locally and added an override for `@polkadot/types`:
```
  "overrides": {
    "@polkadot/types": "file:./../api/packages/types/build"
  },
```
then `yarn install`, `yarn run start`, and navigated to `localhost:3000` in a local browser.

**Comment by iStrike7** [comment]
@serban300 I followed exactly these steps to recreate the changes working.
But it does not work.
![image](https://github.com/paritytech/parity-bridges-common/assets/40371953/fb71381a-b5a6-4b56-942f-2c3b82bc1e05)
![image](https://github.com/paritytech/parity-bridges-common/assets/40371953/4486de70-4948-45af-9d97-1a3d44e1967d)

Did you test this against a local substrate dev node or the Rococo testnet?

**Comment by iStrike7** [comment]
@serban300 
It is not even working with a local substrate dev node
![image](https://github.com/paritytech/parity-bridges-common/assets/40371953/a3e00560-a437-427c-a4f3-13cb0aea7a02)

Are you sure you checked the beefy justification subscription? and not grandpa justification subscription? Because their rpc queries look very similar and grandpa was never the problem...

**Comment by serban300** [comment]
Yes, I tested against rococo and I checked the beefy justification subscription.

I tried to set it up from scratch again. Looks like the field in the `resolutions` section should also point to the local `@polkadot/types` package. Please try these changes: https://github.com/polkadot-js/apps/compare/master...serban300:apps:override-types

Also please make sure to delete the `node_modules` sub-folder inside the `polkadot-js/apps` folder before re-running `yarn install` and also to use a private window for browsing to `localhost:3000` in order to avoid cached versions of the site.

**Comment by iStrike7** [comment]
@serban300 Alright, we have some progress, I am getting some values and data. But what is that format of the output?
I expected a single entry per finalized head. But there are multiple (in the SignedCommitment format)! And some of the signatures seem to be duplicated...
Is this intended or a bug?

**Comment by iStrike7** [comment]
Ideally, imo, it should just print out the SCALE-encoded hex string that represents EncodedVersionedFinalityProof/BeefyVersionedFinalityProof, when BeefyVersionedFinalityProof is encoded it will pack the SignedCommitment (present within BeefyVersionedFinalityProof) into a CompactSignedCommitment. So the subscription should yield the scale encoded EncodedVersionedFinalityProof which is essentially the scale encoded BeefyVersionedFinalityProof which is essentially just (for V1) 0x01 followed by the scale encoded CompactSignedCommitment.
The entire purpose of the CompactSignedCommitment is to reduce the communication overhead.

Thus the return type of the subscription should just be `pub struct EncodedVersionedFinalityProof(sp_core::Bytes);`

**Comment by iStrike7** [comment]
> Thus the return type of the subscription should just be `pub struct EncodedVersionedFinalityProof(sp_core::Bytes);`

I did this locally and it *seems* to be working correctly, exactly as expected. I will need to run it on my beefy decoder and verifier to be confident though.
Note: I am still getting multiple entries for a finalized head, And I think these are proofs with different sets of signatures.
Each proof has 74 signaures (as expected 110 - (110-1)/3), along with a bitfield to know which signature corresponds to which validator as described by the CompactSignedCommitment.
So each proof that is returned is individually valid and you can use anyone of them.

If you allow me access to create a PR with the correct typing, I will do so.

Thank you!
I will update once I finish testing it further.

**Comment by serban300** [comment]
@acatangiu can you please take a look on the questions and suggestions in the latest 3 comments above ?

**Comment by serban300** [comment]
Resolving this issue since the js part is fixed. As discussed above, for the remaining suggestion, let's follow-up in a different PR.
