### ISSUE TITLE
Backport `polkadot-staging` to `master`

### ISSUE THREAD

**Issue by bkontur** [paritytech/parity-bridges-common#2666]
I forgot to backport Rococo/Westend stuff to master, should be this commits:
- [x] https://github.com/paritytech/parity-bridges-common/commit/062449d8cea744b829675f9f39493180134bfe7b
- [x] https://github.com/paritytech/parity-bridges-common/commit/b5c43bbf37fd37184ef283d7e31b02b8dc53638c
- [x] https://github.com/paritytech/parity-bridges-common/pull/2665
- [x] https://github.com/paritytech/parity-bridges-common/pull/2668
- [x] https://github.com/paritytech/parity-bridges-common/pull/2690
- [x] https://github.com/paritytech/parity-bridges-common/pull/2692
- [x] https://github.com/paritytech/parity-bridges-common/pull/2696
- [x] https://github.com/paritytech/parity-bridges-common/pull/2699

~~I can do it on Monday, but no problem if anybody do it sooner, if needed.~~

**Comment by svyatonik** [comment]
I'd add two more things here:
1) merging #2663 to `polkadot-staging`
2) synchronizing list of crates in `master` and `polkadot-staging`. Like why `bp-asset-hub-kusama` and `bp-asset-hub-polkadot` are in the `polkadot-staging`, but not in `master`. For sure, we need to add them to master - it causes confusion :)

I'll probably pick it up, but later

**Comment by svyatonik** [comment]
also https://github.com/paritytech/parity-bridges-common/pull/2670

**Comment by svyatonik** [comment]
https://github.com/paritytech/parity-bridges-common/pull/2673

**Comment by svyatonik** [comment]
https://github.com/paritytech/parity-bridges-common/pull/2690

**Comment by bkontur** [comment]
@svyatonik  thank you :+1: :+1: :+1:  :100:
