### ISSUE TITLE
Investigate optimize Rococo GRANDPA jutification for header  `TooLowCumulativeWeight`

### ISSUE THREAD

**Issue by bkontur** [paritytech/parity-bridges-common#2713]
When I initialized Rococo/Westend bridge live finally I saw some errors like bellow, bridge is working fine now, no problem, but I dont know if this error is something which we have to be afraid of or not, if not, we can close.

```
2023-11-16 17:27:20.700	
[BridgeHubRococo_to_BridgeHubWestend_MessageLane_00000002] 2023-11-16 16:27:20 +00 ERROR bridge Error asking for source headers at BridgeHubWestend::MessagesDelivery: Custom("Failed to optimize Rococo GRANDPA jutification for header HeaderId(7912940, 0xe39fc525c3381c2b6856d95fd2d51faf6c45a8780929864f04a422673606677f): Error::TooLowCumulativeWeight"). Retrying in 0.259515527
```

Grafana (change date 16.11-17.11.2023)

https://grafana.teleport.parity.io/explore?orgId=1&left=%7B%22datasource%22:%22P03E52D76DFE188C3%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bpod%3D~%5C%22bridges-common-relay%2F.%2A%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22P03E52D76DFE188C3%22%7D,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-24h%22,%22to%22:%22now%22%7D%7D

**Comment by svyatonik** [comment]
That's a known issue: https://github.com/paritytech/parity-bridges-common/issues/2415 It happens during authority set changes, so on production chains you shall not see it often

**Comment by bkontur** [comment]
closing as duplicate of https://github.com/paritytech/parity-bridges-common/issues/2415
