### ISSUE TITLE
Monitoring and alerts for Kusama BEEFY

### ISSUE THREAD

**Issue by bkontur** [paritytech/parity-bridges-common#2716]
I am cleaning up a little but monitoring and alerts for Rococo/Westend bridge and I exported and added here: https://github.com/paritytech/parity-bridges-common/pull/2710 stuff for Rococo BEEFY, so the question is, if we want to setup dashboard/alerts for Kusama BEEFY live?

https://grafana.teleport.parity.io/d/3sEDRyl7z/rococo-beefy?orgId=1

**Comment by acatangiu** [comment]
https://grafana.teleport.parity.io/d/3sEDRyl7z/polkadot-kusama-rococo-westend-beefy?orgId=1
