### ISSUE TITLE
Question: can this be used to create a bridge to ZCash?

### ISSUE THREAD

**Issue by muddlebee** [paritytech/parity-bridges-common#2762]
I was reading the README.md it says this is for bridge between two substrate chains. Can you please suggest otherwise?

Sorry for creating an issue here, but I felt this is the best way to reach out to the core contributors.

**Comment by svyatonik** [comment]
No, this codebase is used to build bridges between two chains that are using Substrate framework and sharing some common features. In particular, it is used to [bridge Kusama and Polkadot chains](https://github.com/polkadot-fellows/runtimes/pull/108). Two major requirements for the chain (actually: both chains) to use that bridge are:
- it should be able to plugin our pallets there (see https://docs.substrate.io/reference/frame-pallets/);
- it should use the GRANDPA finality or parachain finality (or BEEFY finality in the future).

ZCash, unfortunately, misses those features, so you won't be able to build bridge with it using this code. ZCash bridge should likely  be based on [Bitcoin bridge code](https://github.com/interlay) with ZCash-specific consensus features applied.

We'll update the README.md to include answer to this question.
