### ISSUE TITLE
Add integration xcm-emulator tests for bridge-hubs to K/P bridging in fellows repo

### ISSUE THREAD

**Issue by bkontur** [paritytech/parity-bridges-common#2791]
Thanks to @acatangiu, we have integration tests in `polkadot-fellows` repo, so now we can add there bridge-hub integration tests for KSM/DOT asset transfer over bridge [here](https://github.com/polkadot-fellows/runtimes/pull/108) as we have for Rococo/Westend [here](https://github.com/paritytech/polkadot-sdk/tree/master/cumulus/parachains/integration-tests/emulated/tests/bridges/bridge-hub-rococo/src/tests)

**Comment by svyatonik** [comment]
> sure, Slava, just take it, but I would suggest wait till I stabilize [polkadot-fellows/runtimes#137](https://github.com/polkadot-fellows/runtimes/pull/137) little bit :) 

I could start something on top of that - not a big deal :)

> what is `zn` ?

I mean https://github.com/paritytech/polkadot-sdk/pull/2439 :)

**Comment by bkontur** [comment]
ahaaaa, I see, you mean that "issue with many debug commits for CI"? :D :D :D

**Comment by bkontur** [comment]
search for `// TODO: uncomment when https://github.com/polkadot-fellows/runtimes/pull/108 is merged` in fellows

**Comment by bkontur** [comment]
this will be merged to the `polkadot-fellows`'s main as a part of https://github.com/polkadot-fellows/runtimes/pull/159
