### ISSUE TITLE
Relayer syncs multiple parachain heads even if no messages are sent

### ISSUE THREAD

**Issue by serban300** [paritytech/parity-bridges-common#2838]
This is causing failures of the `0002-mandatory-headers-synced-while-idle` bridge test in the polkadot-sdk repo

After this is fixed, let's not forget to add the test to the CI

## Reproduction steps ##

1. Clone the polkadot-sdk repo locally: https://github.com/paritytech/polkadot-sdk
2. Set all the necessary env variables https://github.com/paritytech/polkadot-sdk/blob/aa68ea58f389c2aa4eefab4bf7bc7b787dd56580/bridges/zombienet/run-new-test.sh#L21-L40
3. Go to the $POLKADOT_SDK_PATH/bridges/zombienet/environments/rococo-westend
4. Run `spawn.sh --start-relayer`
5. Open the Rococo BH and Westend BH pages in polkadot js apps

## Result ##

On my machine, for example, for Westend BH, the parachain head was updated 3 times even if no messages were sent on the bridge:

![image](https://github.com/paritytech/parity-bridges-common/assets/18124062/898a375e-bd5f-47eb-81ef-a89aa50ac662)

**Comment by svyatonik** [comment]
Fixed in above ^^^ PRs
