### ISSUE TITLE
Add `#[pallet::storage_version` to the all bridging pallets

### ISSUE THREAD

**Issue by bkontur** [paritytech/parity-bridges-common#2947]
Relates to: https://github.com/paritytech/parity-bridges-common/issues/2794
Relates to: https://github.com/paritytech/parity-bridges-common/issues/1869

Addressing comments bellow: https://github.com/paritytech/parity-bridges-common/pull/2873/files#r1562376385

## TODO
- [ ] check `try_state` for bridging pallets

**Comment by acatangiu** [comment]
from discussion in https://github.com/paritytech/polkadot-sdk/pull/4337 it looks like we're not doing this anymore? (although I didn't understand why/how this is not useful anymore)

@bkontur @svyatonik wdyt? if not needed, we can close the issue

**Comment by bkontur** [comment]
we will just add `#[pallet::storage_version` when needed
