### ISSUE TITLE
Polkadot<>Kusama zombienet tests: allow connecting chains from different releases

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#2975]
I was trying to use P<>K zombienet tests some time ago to test a new version of P<>K relayer, but it was hard, because they were outdated. Now we have them merged (:rocket:) and I hope they'll be maintained. I see two cases when those tests need to be used:
1) on new runtimes release - we simply run them. It can probably be moved to CI some day;
2) when we need to build a new relayer, we want to test it. But there's an issue - chains are upgrades quite randomly (at least from my PoV) - so we may have a BHK running on version 1.100.42 and BHP running 1.101. Not to mention relay chains. So I can't be sure that the relayer will be working with BHK 1.100.42 and BHP 1.101 just by running tests from a single `runtimes` commit.

Let's add something to improve handling of (2). The easiest way right now imo is to have two `CHAIN_SPEC_GEN_BINARY` env variables instead of one: e.g. `KUSAMA_CHAIN_SPEC_GEN_BINARY` and `POKADOT_CHAIN_SPEC_GEN_BINARY`. Every binary may be built from its own git commit/tag, so we'll end up with Kusama +BHK running one release and Polkadot + BHP running other.

It isn't superb and we may have a better support for that later.

**Comment by bkontur** [comment]
haha, I didn't know that we have an issue for that,
it is already fixed: https://github.com/polkadot-fellows/runtimes/pull/452
