### ISSUE TITLE
ETH PoW Light Client on Substrate

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#324]
Briding a PoW chain requires a different scheme to verify headers than PoA. In the existing PoA pallet we have, we verify authorities signatures and track authority set changes. We assume finality when over 51% of authorities signed (indirectly) a particular block.

To verify PoW seals we are going to need to verify DAG (light verification), since DAG files are quite big, it makes sense to employ a strategy used by [NEAR's Rainbow Bridget](https://github.com/near/rainbow-bridge-rs/tree/master/eth-client), where DAGs are merkelized and pre-computed for couple of years of runway, then root hashes are simply hardcoded into the pallet. Verifying an Ethereum header requires the header itself + values required by DAG verification and merkle proofs for these values.

Finality of PoW blocks should be assumed after enough confimations (configurable). The bridge pallet should also have a safety valve to recover from a deeper re-organization (optional; we can put it on the chain governance initially).

The bridge pallet should satify #204 interface, and if possible should re-use code from #206 . Alternatively we may consider copying the PoA bridge pallet and altering with different verification scheme in case we are time-constrained.

**Comment by musnit** [comment]
@tomusdrw are you sure DAG files need to be stored/merkelized/pre-computed? https://eth.wiki/concepts/ethash/ethash seems to imply, in step 2, that light clients only need the ~16MB cache and that "Verification can be done with low memory by using the cache to regenerate the specific pieces of the dataset that you need, so you only need to store the cache."

**Comment by tomusdrw** [comment]
The full DAG is indeed not needed, but the 16MBs of light cache is the starting point - this grows alongisde the DAG. AFAIR DAG is approaching (or is already over) 4G, so the light cache had a similar growth.
This value changes every 30k blocks, so we would need to regenerate ~64MBs of data and store it on-chain, which still sounds way too big for something that could be done in the runtime.

**Comment by musnit** [comment]
Another idea could be to generate a limited cache that can for example only verify 10% of headers to save on storage/compute costs, and then verify only every 10th header

**Comment by tomusdrw** [comment]
One more idea was to actually add `ethash` verification to substrate (Runtime Execution Extension), so the PoW verification would be simply off-loaded to the host environment.

**Comment by tomusdrw** [comment]
Closing, since the ETH bridge is being worked as W3F Grant in [polkadot-ethereum](https://github.com/Snowfork/polkadot-ethereum) repositry. Happy to re-open if the outlook changes.
