### ISSUE TITLE
Integrate cargo-spellcheck

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#333]
https://github.com/drahnr/cargo-spellcheck

**Comment by TomaszWaszczyk** [comment]
Ideal way to dive into the rusty and substrate'y way and go through the whole project:

https://twitter.com/tomaszwaszczyk/status/1304751731969064960

Will create PR within a few days.

**Comment by TomaszWaszczyk** [comment]
What if spellcheck does not make sense, like:

![image](https://user-images.githubusercontent.com/1605705/92995256-4257a000-f502-11ea-94bd-b942e9487eb4.png)

**Comment by HCastano** [comment]
Thanks for taking this on! Adding a `cargo-spellcheck` config folder for all our lingo is totally fine.

**Comment by TomaszWaszczyk** [comment]
I wanted to make a Draft Pull Request, what I got:

![image](https://user-images.githubusercontent.com/1605705/93533256-d2eb1180-f942-11ea-835a-ad0f330eae9e.png)

I do want to solve even one 'simple' issue to the repository, in my opinion it is one of the most crucial repository in Polkadot's ecosystem that I why I want to make even small (for creators, not me :D) contribution.

**Comment by danforbes** [comment]
@TomaszWaszczyk I saw your question in #SubstrateTechnical about this Issue. How can I help you with you this?

**Comment by TomaszWaszczyk** [comment]
Great @shawntabrizi helped pretty well! Thanks!

**Comment by TriplEight** [comment]
it's done
