### ISSUE TITLE
Add Dev Account

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#346]
While testing #340 I found myself moving funds from Arthur, Bertha, or Carlos to another MetaMask account. This is because those three accounts are being used for other purposes (e.g submitting CE transactions). This messes up the account nonces and confuses MetaMask, leaving these accounts unusable. 

We should add another account (whose name obviously starts with a D :P) which has some amount of funds endowed, but is not used for anything else.

**Comment by tomusdrw** [comment]
Carlos is not really used for anything, afair, but added Diego in #347
