### ISSUE TITLE
UI types are outdated

### ISSUE THREAD

**Issue by Tbaut** [paritytech/parity-bridges-common#358]
The console in [the UI](https://paritytech.github.io/bridge-ui/) shows that the api found unknown types:
> Unknown types found, no types for InstanceId, MessageId, Receipt, SpecVersion, TransactionInclusionProof

Can we update the types (we can copy that over from https://github.com/paritytech/parity-bridges-common/blob/master/deployments/types.json to https://github.com/paritytech/bridge-ui/blob/master/src/customTypes.ts )

Not sure if the 2 are related, but it's not showing the blocks from the pallet any more, they remain 0.
![image](https://user-images.githubusercontent.com/33178835/93369574-d9e52780-f84f-11ea-855b-2d01ef16bc3b.png)

**Comment by tomusdrw** [comment]
Just adding to the issues that we should add custom types for the new Message Lanes and Substrate Bridge Pallet as well when we are up updating them.

**Comment by tomusdrw** [comment]
Closed via #882 & #706
