### ISSUE TITLE
Steps required to setup and operate PoA -> Substrate bridge

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#36]
Get all the required things to run PoA -> Substrate one way bridge (with #26).

Stuff like:
- [ ] Required machines and clients (get in touch with devops team)
- [ ] Monitoring (and some basic failure detection, possibly post in the riot channel) 
- [ ] Status page
- [ ] Westend Runtime Upgrade process (who & how)
- [ ] Clarify API required from the PoA header chain module (most likely `verify_event` and `verify_transaction`. Maybe `verify_storage`?).

**Comment by HCastano** [comment]
I think we should start by running a chain based off the code in `bin/node` instead of jumping straight to Westend. Once we think that's running well enough then we could propose a runtime upgrade.

**Comment by tomusdrw** [comment]
Split into more concrete issues, so #163 should close this.
