### ISSUE TITLE
Add Message Passing Stats to Grafana

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#363]
Right now we only have Grafana dashboards for our header sync. It would be cool to see something similar for our message passing application. Some things I'd like to see would be: number of messages delivered, number of messages dispatched, number of pending messages, and race stats for different lanes.

cc @svyatonik since you might have some ideas on what else would be useful to monitor.

**Comment by tomusdrw** [comment]
Closed via #520 #533
Let's create separate issues for more specific dashboards.
