### ISSUE TITLE
Decouple Source and Target Header/Hash/Number Types

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#366]
The Substrate pallet right now assumes that both the source and target chain have the same types. This is seen through the use of `T::Header` and its associated types. Ideally we want to make this configurable through the pallet's configuration trait.

For more info see [here](https://github.com/paritytech/parity-bridges-common/pull/296#discussion_r490083775).

**Comment by svyatonik** [comment]
This is done in #375
