### ISSUE TITLE
Publish Millau Bridge Node Docker Images

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#373]
While making changes for #372 I was tempted to change the publishing action to include the Millau node. However, as it's not used for anything right now (need to wait until we integrate the Substrate pallet) I figured it would be a waste of server time and space. I did want to note it down though since this is something we'll need to do further down the line.

**Comment by tomusdrw** [comment]
Isn't this already done in #464? @HCastano please reopen if that's not the case and provide more details what still to be done.
