### ISSUE TITLE
Only accept headers-in-unsigned-transactions when we know we're almost at the tip of PoA chain

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#38]
extracted point(4) from #26, because it'll need another round of research:
...
4) one other restriction that we may introduce: we know approximate block time of PoA (it is stepDuration...stepDuration * maximumEmptySteps) - what if we only accept unsigned transactions when we believe we're at the tip of PoA chain (i.e. when timestampModule.timestamp - BestKnownPoAHeader.timestamp < N * approximateBlockTime)?
...

Need to be caution with computing approximate block time, because (c): "there were some issues recently on network (running some super old PoA), where after upgrade the current step and "expected step" did not really fully match. I.e. due to some time drifts, validators being down, etc the step calculated from stepDuration did not match the actual step in the network. Maybe if we make it relative, i.e. using the step from the last known block as a reference point, this could work"

**Comment by svyatonik** [comment]
Another possible optimization: https://github.com/paritytech/parity-bridges-common/pull/45#discussion_r402970795

**Comment by tomusdrw** [comment]
Closing, since we don't plan to actively work on the PoA bridge in the near future. Happy to re-open if the outlook changes.
