### ISSUE TITLE
The sender should give max declared weight to be consumed on the target chain.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#384]
The `MessageLane::send_message` accepts any payload currently (see #383). The idea was that the message lane will delegate to the verifier, to make sure the payload is safe to dispatch on the target chain.

However the verifier, might not be able to decode the payload to actually estimate the `weight` that would be consumed on the target chain.
Because of that, if the sender submits a call that would consume more than `MaximumBlockWeight` of target chain, the relayer wouldn't be able to deliver such call here:
https://github.com/paritytech/parity-bridges-common/blob/4f3bd898f46cad3f2d223856791e30c119e8ec7f/modules/message-lane/src/lib.rs#L246
which would effectively lock the lane.

The idea is that:
1. The sender should provide `declared_max_weight` when sending the message
2. The verifier can use this to make sure it's within sane limits and should also make sure that it pays for the bytes being delivered (to prevent cheaply sending large amounts of data).
3. On the target side (when receiving a message) we use `declared_max_weight` as a lower bound of the weight provided by relayer.
4. We compare the `declared_max_weight` vs weight decoded from the `Payload` and fail the dispatch with a special error in case we would consume more than `declared_max_weight`.

**Comment by svyatonik** [comment]
@tomusdrw I was going to work on this today, but then realized that the `weight` is already declared by sender. Sorry that I've maybe confused you yesterday - was too busy with other PRs. In our target deployment configuration (i.e. message lanes module + call-dispatch) it is a part of [call_dispatch::MessagePayload](https://github.com/paritytech/parity-bridges-common/blob/master/modules/call-dispatch/src/lib.rs#L77). So both the `LaneMessageVerifier` and relayer will have access to that declared weight.

So as I see it, on source chain the `OutboundPayload` will be declared as something like `call_dispatch::MessagePayload<Call = Vec<u8>>`, so all fields except `Call` are decodable+accessible by all 'players'. On target chain, the `InboundPayload` will be declared as `call_dispatch::MessagePayload<Call = Runtime::Call>`.

Adding new `weight` argument to the `send_message()` function imo isn't good idea. E.g. if all messages are designed to have the same weight (e.g. if we're only dispatching currency transfers between existing accounts), then what/why we need to specify that explicitly.

If you're not ok with this ^^^, could you, please, respond? If you're ok, then, please, do not close the issue now - it is important to keep this in mind during Runtime-integration and relay-deployment.

**Comment by tomusdrw** [comment]
Yeah, that sounds good! Better to keep this on `dispatch` layer if possible, so I think we're covered. Keeping the issue open so that we pay attention to proper declared weight vs expected weight verification,.

**Comment by svyatonik** [comment]
closed by #386
