### ISSUE TITLE
Add Benchmarking to Millau Runtime

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#390]
The Millau runtime does not have any benchmarking capabilities at the moment. We need to set that up in a similar fashion as we have done with the Rialto runtime

**Comment by tomusdrw** [comment]
Is it required for any feature? Closing, since I think weights are covered in #391 and I don't see a reason just to have benchmarking for Millau, just for the sake of having it :)

**Comment by HCastano** [comment]
> Is it required for any feature? Closing, since I think weights are covered in #391 and I don't see a reason just to have benchmarking for Millau, just for the sake of having it :)

No, I don't think this is required anymore. The main thing for benchmarking is that we have a good benchmark framework for each pallet, and that we know they compile with at least one runtime (in our case that's Rialto). We can then automate benchmarking with our "production" runtimes (e.g Kusama).
