### ISSUE TITLE
Use Automated Benchmarking for Runtimes

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#391]
As previously mentioned in #78, Substrate has gotten a feature where we're able to automatically generate weights for pallets based on the current runtime configuration. We should use this feature to benchmark the Rialto and Millau runtimes (and their included pallets).

For further reading see [here](https://github.com/paritytech/substrate/tree/master/frame/benchmarking).

Related: #78, #390 

**Cumulus repo:**
- `bridge-hub-kusama` - `type Weigher = ` according to `bridge-hub-rococo -> BridgeHubXcmWeight` 
- https://github.com/paritytech/cumulus/blob/bridge-hub-rococo-wococo/parachains/runtimes/bridge-hubs/bridge-hub-rococo/src/weights/xcm/mod.rs#L216-L223
```
fn export_message(_: &NetworkId, _: &Junctions, _: &Xcm<()>) -> XCMWeight {
		log::error!(
			target: crate::LOG_TARGET,
			"TODO: Calling weight: export_message -> triggers unpaid_execution -> need fix here!"
		);
		// TODO:check-parameter - add correct weight also add it to the polkadot gav-xcm-v3
		XcmGeneric::<Runtime>::unpaid_execution().ref_time()
	}
```

**Comment by tomusdrw** [comment]
See #815

**Comment by tomusdrw** [comment]
I believe this is handled automatically in the Polkadot repository while releasing, but leaving it here just to make sure.

**Comment by svyatonik** [comment]
I'll move it to K<>P milestone, as it is not super-relevant for testnets and it is better to implement it with next `bridges` subtree update

**Comment by svyatonik** [comment]
Done in https://github.com/paritytech/polkadot/tree/bridges-integration-with-council-support . Will close this issue once we have this branch merged

**Comment by svyatonik** [comment]
Benchmarks for RBH/WBH are ready and weights are gemnerated by bench bot
