### ISSUE TITLE
Introduce import context type

### ISSUE THREAD

**Issue by adoerr** [paritytech/parity-bridges-common#415]
Both `import::import_header()` and `import::import_headers()` currently have too many parameters. 

Introduce an import context type which should be used as a container for the parameters. Such a struct might also allow for some sort of default import context.

**Comment by HCastano** [comment]
A little bit more context can be found [here](https://github.com/paritytech/parity-bridges-common/pull/410#discussion_r502866886).

**Comment by tomusdrw** [comment]
Obsolete via #1210
