### ISSUE TITLE
Create Dev Config for Rialto PoA

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#416]
As mentioned in #414 the `dev` and `rialto` configuration parameters don't match up when trying to use the dev scripts in `./scripts` to run a simple Ethereum to Substrate network. One thing we could do is introduce a `rialto_poa_dev.rs` config which has the correct parameters (`state_root` and `genesis_validators`). However, this would require adding another instance of the pallet to the runtime which is a little unfortunate.

Maybe we can solve this using #407 by using the same instance of Rialto PoA we already have but overriding the parameters for the dev network after launch?

**Comment by tomusdrw** [comment]
Why not provide a conditionally-compiled version which supports the dev chain genesis instead of a Rialto Poa?

**Comment by HCastano** [comment]
I wanted to avoid feature flags since it makes development and testing a bit annoying (additional features to turn on and check), but yeah I can look into it

**Comment by tomusdrw** [comment]
Good point, we can have the default to be `dev` then and compile docker images with the feature enabled (since it's automated anyway), wdyt?

**Comment by adoerr** [comment]
Would the configuration have to be compiled in? Perhaps some sort of `--cfg-file` CLI argument reading in some external configuration file would be useful. This CLI argument would be optional. If not present, a compiled in default configuration is used. 

Personally I do view the locally deployed and manually started node configuration as a valuable test tool in addition to the unit tests. Another approach would be to have specialized test nodes which could be configured even more. But that is definitively a more laboriously approach.

**Comment by acatangiu** [comment]
Made obsolete by https://github.com/paritytech/parity-bridges-common/pull/1210
