### ISSUE TITLE
Prune Headers in Substrate Pallet

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#419]
Splitting out of #369.

For storage reasons we don't want to be keeping old headers around. We should have a way to prune these headers from storage which is configurable (e.g choose how many headers you want to keep at any point in time, or how many to remove in one go). While pruning headers on the non-canonical chain is important, we should also be able to prune old headers on the canonical chain. Again, this is for storage reasons.

**Comment by tomusdrw** [comment]
I didn't have time to finish this up, might be worth re-visiting now with Finality Verifier pallet being in.
