### ISSUE TITLE
Prevent Grandpa Equivocations

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#430]
Grandpa equivocations occur when somebody _votes_ on two or more different things in the _same round_. When the Substrate pallet imports a finality proof (Grandpa justification) we don't check if we've already accepted the same justification in the same round.

Two things worth noting:
- We are allowed to import _different_ justifications in the _same_ round
- The same authority set (same `set_id`) is allowed to vote on the same thing in a _different_ round

A practical example of the second point is that Grandpa can finalize the same block twice, as long as it's finalized on different rounds. This helps uphold liveness and consistency guarantees in Grandpa.

**Comment by tomusdrw** [comment]
I believe this is already done as part of #629, no? @HCastano please re-open if it's still valid.
