### ISSUE TITLE
Integrate with Polkadot & Kusama runtimes

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#438]
Figure out if forking the repo is required (simlar to #218). Instead of bridging directly with the relay chain, maybe it's a better idea to deploy a parachain - this depends on the parachain availability.

**Comment by HCastano** [comment]
I think we should look into integrating as a parachain. I'm not sure if the Polkadot council will approve of a bridge being added to the relay chain since it could potentially introduce "bloat".

**Comment by tomusdrw** [comment]
A tentative integration in https://github.com/svyatonik/polkadot/commits/bridges-integration

**Comment by tomusdrw** [comment]
We need to make sure to tune weight-related constants for the polkadot / kusama integration.

**Comment by svyatonik** [comment]
https://github.com/paritytech/polkadot/tree/bridges-integration-with-council-support

**Comment by svyatonik** [comment]
We no longer plan to deploy our pallets at Kusama/Polkadot directly, so this issue is no longer actual
