### ISSUE TITLE
Refund submitters of duplicate headers (Sub Bridge pallet)

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#439]
It's possible that some headers sent by two different relayers would overlap and only one of them would be imported successfuly.
To reduce excessive cost for the relayer we might consider refunding some of the weight for headers that we recognize as duplicates.

Note that the relayer will stay pay for this, but we just reduce the amount they are going to pay.

**Comment by EmmanuellNorbertTulbure** [comment]
@svyatonik is this still relevant for our goal?

**Comment by svyatonik** [comment]
It is fixed already
