### ISSUE TITLE
Relayer should support initial header to start from

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#442]
Initially when the substrate pallet is going to be deployed the sync will be temporarily frozen.
At some point we will initialize the pallet with a starting block and enable sync.
Main reason for that is the delay between runtime upgrade proposal and enactment, we can hardcode the starting block in the runtime upgrade, but then after the enactment of upgrade the bridge will be extremely behind the other chain and will have to catch up.

Related: #440 - the relayer should handle the case if header sync is frozen.

**Comment by HCastano** [comment]
Here is the related runtime issue: #407. I think that needs to be tackled before we add support in the relayer.
