### ISSUE TITLE
Message dispatch filtering

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#450]
The dispatcher #211 should support a whilelist of calls that can actually go past the bridge. It should go beyond simply .call type, rather we might want to filter out specific parameters as well (to make sure they are in range, or to only have a limtied set of transfers initially (limited in value)).

**Comment by svyatonik** [comment]
Since it is very chain-specific, it probably should be done at the runtime level, where `message-lane` <-> `call-dispatch` communication happens. I.e. in the implementation of `bp_message_lane::MessageDispatch`. So we just add additional filter there, before message is actually passed to the `pallet_bridge_call_dispatch::Module`.

**Comment by tomusdrw** [comment]
I wonder if there is something we could and should do on the source chain as well? We most likely don't want to decode the entire call, but we could simply check the first byte of the payload?

**Comment by tomusdrw** [comment]
This is runtime specific, so should be part of the concrete release (Kusama <> Polkadot).

**Comment by adoerr** [comment]
Would it be useful to allow for dynamic filters (using `frame_support::traits::FilterStack`) as well? This could even go as far as offering a `sudo` call in order to add and remove filters.

**Comment by tomusdrw** [comment]
`Filter` trait covers `FilterStack` as well (see `impl_filter_stack` macro in substrate), so the way it's implemented in #687 is good enough :)

**Comment by tomusdrw** [comment]
Implemented in https://github.com/paritytech/polkadot/tree/bridges-integration-2
