### ISSUE TITLE
Sync Kusama to Millau

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#451]
Introduce unidirectional sync between Polkadot / Kusama to Millau to make sure we can actually sync it.

Come up with a more detailed plan how to test bridges.

**Comment by tomusdrw** [comment]
I've renamed the issue, since the rest of the "testing plan" is being realised right now:
1. Running test bridge with Kusama
2. High level documentation (#565)
3. Internal & External audits
4. Deployment details

**Comment by svyatonik** [comment]
We now have this Westend (more or less Kusama) -> Millau bridge. Imo adding another one won't be super-useful.
