### ISSUE TITLE
Disallow Importing Headers on Abandoned Forks

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#454]
At the moment the Substrate pallet does not perform checks on incoming headers to see if they are on an unfinalized fork. 
This is a problem because we may continue importing headers on a fork which can never be finalized. Consider the following case:

```
Import Order: 1, 2, 2', F2, 3', 4'

    / [2'] <- [3'] <- [4']
[1] <- [2: F]
```

Right now we're allowed to import (but not finalize) headers `3'` and `4'` because they're at a higher height than our best finalized header (`2`). We can keep building on this fork indefinitely but we'll never be able to finalize anything (since that would compete with the already finalized fork). 

Since the Substrate pallet follows the longest chain rule for picking the best header we'll consider the headers on fork 2 to be the best which may prevent the relayer from making progress on the canonical chain.

We need some way to determine which fork we're on without doing expensive ancestry checks every time we import a header. This way we'll be able to know if we're building on top of an abandoned fork and disallow imports.

Related conversation [here](https://github.com/paritytech/parity-bridges-common/pull/409#discussion_r509081703).

**Comment by tomusdrw** [comment]
Closing as irrelevant now, we only import headers which have finality proof.
