### ISSUE TITLE
Chain-specific runtime message-delivery API

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#457]
Right now message delivery APIs (`OutboundLaneApi` and `InboundLaneApi`) are not chain-specific and thus the runtime can't provide APIs to bridge more than one chain. The way we have solved this in headers sync is that we have separate API trait for every chain (i.e. `RialtoHeaderApi` and `MillauHeaderApi`). The same should be done here - i.e. we should have `RialtoOutboundLaneApi`, `RialtoInboundLaneApi`, `MillauOutboundLaneApi` and `MillauInboundLaneApi`.

The alternative implementation is to add additional argument (`instance: InstanceId`) to all methods. It is hard-to implement in the runtime (without some macro helpers), but it is more convenient for the relay. So probably worth trying this option and then in separate PR also migrate `HeaderApi` to that version.

**Comment by tomusdrw** [comment]
Related: #446
