### ISSUE TITLE
Test BridgeStorage trait

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#46]
There are now 2 `trait Storage` implementors in PoA module: [`InMemoryStorage`](https://github.com/paritytech/parity-bridges-common/blob/b4877dbf87da88c843be57771c6a05d4cdd0426d/modules/ethereum/src/lib.rs#L765) and [`BridgeStorage`](https://github.com/paritytech/parity-bridges-common/blob/b4877dbf87da88c843be57771c6a05d4cdd0426d/modules/ethereum/src/lib.rs#L383). When the module was created, I've used in-memory storage to embed everything in parity-ethereum. #45 adds more logic to some storage methods && there are no actual tests for it.

So we either need to: (1) add tests for `BridgeStorage`, or (2) change all existing tests to use `BridgeStorage`.

**Comment by tomusdrw** [comment]
I'm reworking the traits a bit as part of #31. The storage becomes more low-level and the logic within `BirdgeStorage` is now extracted to a struct and made more testable. Just FYI, because I think this issue should not be blocked, since all work done can be re-used with the new approach anyway.
