### ISSUE TITLE
Make Monitoring Component Optional in Bridge Deployments

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#484]
At the moment, bridge deployments override a shared monitoring Compose file to set up their own Prometheus and Grafana dashboards. However, the bridge Compose file has these override stubs which don't have an `image` field. This means that they can't be run without a base monitoring Compose file which _does_ have an `image`.

Ideally we would like the bridge deployments to be flexible enough to run without monitoring. One thing we can do (although it's a little bit of a hack) is to have the bridge deployment components use a dummy base image (like `alpine`). If we decide to include monitoring the `alpine` image would be overridden by the appropriate `prometheus` and `grafana` image.

Related discussion [here](https://github.com/paritytech/parity-bridges-common/pull/464#discussion_r517972724).

**Comment by tomusdrw** [comment]
Closed via #689
