### ISSUE TITLE
Allow Substrate Pallet to be Re-Initialized

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#490]
The Substrate pallet is only allowed to be initialized once at the moment. However, there's some use to being able to restart the pallet at a later point in time

Why might we want to do this? One reason could be that the chain we were bridging fell under attack and the pallet ended up on a bad fork. Another could be that no relayers submitted headers for a prolonged period of time, making it hard for the pallet to catch up to the tip of the bridged chain on its own.

To perform a re-initialization we need to clear old storage entries to ensure that new incoming headers and proofs don't conflict with the previous state of the pallet. It is also important that only `Root`/`Owner` has the ability to perform this re-initialization.

**Comment by EmmanuellNorbertTulbure** [comment]
We will rely on governance
