### ISSUE TITLE
Relay Thinks it Successfully Initialized Already Initialized Chain

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#495]
While working on the Rialto<->Millau deployment I ran into an issue where the relay initialization command would run successfully, but then I'd end up with an error saying (more or less, this isn't a copy paste) "X chain thinks header from Y is orphaned". This means that the initialization didn't actually succeed. The problem was that I was trying to initialize a chain which had already been initialized through the chain spec (and it had an outdated `state_root`).

I think what's happening is that we successfully submit the transaction, but we don't check if it _actually_ succeeds. What we should be doing is checking if the dispatchable ran without any errors, and if not warn the user that the pallet has already been initialized.

Steps to reproduce:
- Add GenesisConfig to a node (e.g Rialto) with random data
- Run Rialto and Millau nodes
- Run relay initialization script (will succeed)
- Run relay header sync (will fail here)

cc @svyatonik

**Comment by svyatonik** [comment]
Relay now checks if pallet is already initialized
