### ISSUE TITLE
Containers Take a Long Time to Stop

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#505]
Whenever I stop a deployment (`docker-compose down`/`run.sh ... stop`) I've noticed that most of the containers take a long time (10-15s) before they actually stop. I'm not sure what the cause of it is, but it's something we should look into.

**Comment by serban300** [comment]
According to the [docker documentation](https://docs.docker.com/engine/reference/commandline/stop/#extended-description), on `docker stop`, the main process inside the container will receive `SIGTERM`, and after a grace period, `SIGKILL`.

Looking if our entrypoint scripts handle SIGTERM correctly
