### ISSUE TITLE
Check header timestamp against timestamp module

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#51]
https://github.com/paritytech/parity-bridges-common/pull/45/files#diff-78128fbffca4ac7effa57faf86586991R205

We could perform optional checks against `frame_timestamp` module if available. This should be implemented via associated type (don't reference `frame_timestamp` directly) and should be optional.

**Comment by svyatonik** [comment]
Another benefit of having this fixed. Right now, the logic of relayer is simple:
1) it submits bunch of headers to target node;
2) it waits until either `best_block` is updated, or timeout is elapsed;
2.1) if `best_block` is updated, relayer goes to (1);
2.2) if timeout is elapsed, relayer 'restarts' sync process (i.e. it forgets all headers) and goes to (1).

The bad thing about PoA -> Substrate sync is that if we don't make timestamps checks, then some authority may submit header with step too far from the future => this header will be marked as best. This header will stay best until we'll finalize some ancestor of this block (given #137 is fixed). This may cause pauses in headers relay.
