### ISSUE TITLE
Allow Relayer to Wait on Successful Initialization Before Syncing Headers

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#510]
At the moment we have two individual commands to initialize the bridge and to sync headers across the bridge. Even though this is not expected to be a common workflow in a production environment, for our test deployment we have shell scripts that perform the initialization, and then immediately after try and sync headers. We've been running into race conditions where the relayer tries to sync headers before we successfully initialized the bridge, leading to bad data being returned from the bridge pallet.

It would be useful to be able to wait on a successful initialization before starting to sync headers. One solution could be to introduce an optional `--init` flag to the header sync command(s). What this would do is to first call the `initialize()` dispatchable, wait for a successful result (see #495), and then start syncing headers (since we're now in a known valid state).

**Comment by svyatonik** [comment]
Relay now checks if the pallet is in operable state
