### ISSUE TITLE
Unified Bridge Grafana Dashboard

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#513]
At the moment we have separate Grafana dashboards for each side of a bridge deployment. It would be nice to have a third dashboard which was able to provide important "at-a-glance" information about the state of the entire bridge. This dashboard should _not_ be responsible for things like alerting. Instead that should be left to the side-specific dashboards. The side-specific dashboards should contain some details (like CPU or memory usage) which would be otherwise unimportant to a casual viewer.

There's a tiny bit of conversation around this in #502, but nothing that wasn't said here.

**Comment by tomusdrw** [comment]
Addressed by https://github.com/paritytech/parity-bridges-common/pull/881
