### ISSUE TITLE
LaneMessageVerifier re-usable implementation

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#521]
Every mesasage that you attempt to send via `message-lanes` pallet can be verified by `LaneMessageVerifier`.

This can be used to apply any lane-specific verification, but should also be responsible for whitelisting particular lane ids.

Since the undelivered messages can be sent by anyone and are stored on-chain, we should prevent excessive growth of on-chain data, we also don't want to upgrade this parameters via runtime upgrade every time there is a new lane that is supposed to be handled.

The verifier should support:
- Whitelisting `lane_ids`.
- A `max_outbound_messages` per every whitelisted `lane_id` (setting non-zero can basically be the whitelist)
- Checking minimal `delivery_and_dispatch_fee` - even though the message would pay, we need a fee that will cater for the fixed cost of the chain + relayer to simply have that message delivered & processed.
- Re-using verification logic for existing lanes.
- An admin account to tune these parameters.

Any lane-specific logic (like checking the `dispatch_weight`) would need to be implemented by a runtime upgrade, but I suspect there might be some functionality that could simply benefit from default values and existing lane-specific verifiers. Imagine that we just want to increase the throughput of the bridge by adding a second identical lane managed by a different relayer. We have ordering within the lane, but multiple lanes can progress in parallel.

**Comment by EmmanuellNorbertTulbure** [comment]
@svyatonik is this still relevant in our XCM case?

**Comment by svyatonik** [comment]
> @svyatonik is this still relevant in our XCM case?

Partially, but yes
