### ISSUE TITLE
Token swap pallet

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#543]
It would be cool to have a very simple mechanism of swapping the tokens between bridged chains (think KSM<>DOT).

We could use `atomic-swap` pallet from Substrate repo, but with bridges we can use simpler mechanisms to achieve the same.

Order matching would happen off-chain, the pallet should only be responsible for actually performing an atomic exchange of the tokens.

There should be two workflows possible, depending on whether the pallet is included on both chains or not.

## If both chains include the `Swap` pallet.
1. `source::Alice` and `target::Bob` agree to exchange `source(X) tokens <-> target(Y) tokens` and they pick a `random_nonce`.
2. `let transaction_id = hash(random_nonce ++ source::Alice ++ target::Bob ++ source(X) ++ target(Y))`
3. Both send a similar transaction on their respective chains. Let's analyze Alice's case.
4. `source::Alice` sends a transaction to the pallet:
```rust
source::Swap::exchange(random_nonce, target::Bob, source(X), target(Y));
```
5. The pallet then:
5.1. Lock's Alice's `source(X)` tokens (or transfers them to `source::derive_account_id(transaction_id)`) and stores that fact.
5.2. Send a transaction over the bridge on Alice's behalf (`CallOrigin::SourceAccount(source::Alice)`) with these details:
```rust
target::Swap::claim(random_nonce, target::Bob, source(X), target(Y));
```
6. Depending on the target pallet state (Bob's sent his `exchange` or not) there are two things happening:
6.1. The `target::Swap` pallet records the `claim` under `transaction_id` if Bob has not sent the exchange transaction. If Bob sends the `target::Swap::exchange(random_nonce, source::Alice, source(X), target(Y))` transaction, the tokens are immediately transferred to Alice (like in 6.2) and a `source::Swap::claim` call is sent over the bridge.
6.2. The `target::Swap` performs a transfer for `target(Y)` tokens from `target::derive_account_id(transaction_id` to `target::derive_account_id(source::Alice)` or unlocks Bob's tokens and sends them to `target::derive_account_id(source::Alice)`.
7. Data stored in the pallet in both `target::Swap::claim` and `source::Swap::exchange` expire after a period of `1 day` and `2 days` respectively and the funds locked in `exchange` are redeemable by the original owner.

There is a risk for Alice to have her funds locked for 2 days if Bob decides not to publish his transaction. This could be solved bif Bob shared his signature over a "cancel order" with Alice, which she can use to cancel the transaction. This signature would have to be wrapped in a `target `chain transaction, and would cancel the claim on the target chain & send a message over the bridge to cancel the `exchange` on the source chain.

## If only `source` chain includes the `Swap` pallet.
The workflow:
1. `source::Alice` and `target::Bob` agree to exchange `source(X) tokens <-> target(Y) tokens` and choose unique `random_nonce`.
2. `source::Alice` requests from `target::Bob` a signature for `signed_message` defined as below:
```rust
let transaction_id = hash(random_nonce ++ source::Alice ++ target::Bob ++ source(X) ++ target(Y))
let bob_account_id_on_source = source::derive_account_id(target::Bob);
let alice_account_id_on_target = target::derive_account_id(source::Alice);
// the account id we derive from the transaction id
let lock_account_id = target::derive_account_id(transaction_id)
// a signature which can be used with `CallOrigin::TargetAccount(lock_account_id, target::Bob, bob_signature)`
// this will allow the bridge to perform a transfer on Bob's behalf.
let bob_transfer = target::Transfer(target::Bob, alice_account_id_on_target, Y);
let bob_signed_message = ( bob_transfer ++ lock_account_id );
```
4. `source::Alice` calls into the pallet with:
```rust
source::Swap::start_swap(random_nonce, target::Bob, source(X), source(Y), bob_transfer, bob_signature);
```
5. The pallet locks `source::Alice`'s funds (or transfers them to `lock_account_id`) and sends the `bob_transfer` message over the bridge using `CallOrigin::TargetAccount(lock_account_id, target::Bob, bob_signature)`.

6. Currently neither the delivery mechanism nor dispatch doesn't relay the result of dispatch back to the source chain (i.e. on the source chain we only know the message was delivered, but we don't know if it dispatched successfully). I think it's worth changing (shouldn't be that complex) - but there is an alternative solution, which requires Bob sending locking his funds in a temporary account first (with some option to transfer back by sending Alice's signed-call on the source chain).

7. Assuming after some time we know the result of the dispatch on the source chain, we can now proceed to either:
7.1. Bob claiming Alice's locked funds. Since Bob interacts with the target chain, he would send a message over the bridge (using `CallOrigin::SourceAccount(target::Bob)`). This call should only succeed if the transfer dispatch was succesful.
```rust
source::Swap::claim_swap(random_nonce, source::Alice, source(X), target(Y))
```
7.2. Alice unlocking her funds by sending `source::Swap::cancel_swap(random_nonce, target::Bob, source(X), source(Y));` which should only succeed if the transfer dispatch failed. 

In this scheme Alice pays all the fees and is more in risk in case Bob doesn't have enough funds on the target chain (or front-runs the bridge message), but there is no time-locking involved. In a happy case the "cost" of the swap is very similar - i.e. each party sends exactly one transaction on their respective chains.

**Comment by tomusdrw** [comment]
To alleviate `bob_signature` re-use [problem](https://github.com/paritytech/parity-bridges-common/pull/944#issuecomment-829145657) found by @svyatonik  in Variant 2 (only Source has the pallet) we can require that `random_nonce` starts with `current_block_number / X` during `source::Swap::start_swap` and make sure we keep used `transaction_ids` for at least `X` blocks. This will make it impossible for `Alice` to re-use the same `transaction_id` if transfer is finished succesfuly.

**Comment by svyatonik** [comment]
> To alleviate `bob_signature` re-use [problem](https://github.com/paritytech/parity-bridges-common/pull/944#issuecomment-829145657) found by @svyatonik in Variant 2 (only Source has the pallet) we can require that `random_nonce` starts with `current_block_number / X` during `source::Swap::start_swap` and make sure we keep used `transaction_ids` for at least `X` blocks. This will make it impossible for `Alice` to re-use the same `transaction_id` if transfer is finished succesfuly.

There are couple of problems with this approach:
1) there's no guarantee that transaction that is submitted at block `N` will be 'mined' in window `[N / X; 1 + N / X]`. The closer is end of the fixed window, the larger are chances that the tx will miss its window and will be rejected;
2) the fact that we need to remember ids of (even finished) transactions (swaps) during `X` blocks means that we need to prune this container somewhere later. TBH I'd avoid pruning at all costs - there are many ways to do that, but every way has its own flaws. E.g. doing that from `on_initialize` means two additional storage updates on every swap start (also may lead to overweighted-after-initialize block). Doing that from claim/cancel means even more additional storage accesses.

I still can do that ^^^, but I have an alternate suggestion. WDYT about claim-locked-period? Like claim/cancel can only be called after `X` block have been created after claim has started. This way transactions ids are stored in natural way, because transactions are not yet finished (solves (2)). There's no problem from (1), because nonce may be selected so that it is valid for `X` blocks starting from any (most obviously - next) block `N` => there are no fixed windows. I know that it looks like time-lock that you've probably wanted to avoid. But anyway - WDYT? We may even allow to configure `X` for every swap (and include it into signed message), so that Bob would know when he may expect swap to happen without looking at pallet configuration.

**Comment by tomusdrw** [comment]
I'm not sure I fully get your idea, let me re-phrase what I understood and please point any discrepancies:
1. So we remember block `N` at which we received `start_swap` alongside `transaction_id`.
2. Bob can only `claim_swap` after block `N + X`, and similarly Alice can only `cancel_swap` after `N + X` block number.
3. This ensures that between `[N; N+X]` blocks Alice won't be able to send the same `start_swap` again (i.e. re-use Bob signature).

What I'm missing is that after these `X` blocks pass and Bob claims his funds Alice can still re-use the same signature, no?
I wanted to avoid a situation where Bob is required to claim his funds within some fixed time period, if your solution does not involve that then it's good :) Like I consider Bob being on a worse position here, cause he has to rely on Alice to perform the swap, hence I don't want him to be even more stressed about potentially going off-line, being censored or the bridge being slow problems.


> The closer is end of the fixed window, the larger are chances that the tx will miss its window and will be rejected;

Good point, the fixed window is quite cumbersome. Maybe we can have dynamic window size then? If we `let random_nonce = valid_until_block_number ++ really_random_nonce;` then we only rely on the assumption that Alice will send the transaction and it will be included within `valid_until_block_number - current_block_number` blocks. It still does involve pruning though.

**Comment by svyatonik** [comment]
All is correct. The signature that Bob is producing is only valid up to given block `B` (it is included in the signed message). Starting from block `B` he could claim hist funds.

> Like I consider Bob being on a worse position here, cause he has to rely on Alice to perform the swap, hence I don't want him to be even more stressed about potentially going off-line, being censored or the bridge being slow problems.

Ok, if you consider that this is more important than lower fee, then I'll try to do something without locking funds.

**Comment by svyatonik** [comment]
@tomusdrw Actually - I misread some of your words :)

> a situation where Bob is required to claim his funds within some fixed time period, if your solution does not involve that then it's good :)

Bob has no any fixed time period **to claim his funds**. Instead he has a period where he **can't yet claim his funds**, even if transfer at target chain has happened. and it is already confirmed  to the source chain. It is exactly what you've described in (1) - (3). I believe your concern with "Bob being on a worse position here" is still valid, though. Because Bob, which acts at the target chain, needs to track source chain blocks to be sure that his `claim_swap` message will succeed. Does it falls under "then it's good" category?

**Comment by tomusdrw** [comment]
>  is only valid up to given block B (it is included in the signed message).

Oh, okay. I think we are on the same page now. So basically it's more like the "dynamic window size" I've mentioned later, but with a little bit different trade-off: we don't implement pruning, but Bob has to wait a bit to claim his funds.

> Does it falls under "then it's good" category?

Yes, I think it's good enough. With `B` (`valid_until_block_number`) exposed we can also easily reject old messages (I'd actually do that on the transaction pool level, so that Alice doesn't have to pay fees, but it's more of an "nice-to-have" addition than a requirement).


I'd still explore a possibility of finishing the transfer early, or reduce the timeing, maybe let Bob do something like `claim_unsafe` - because if Bob simply ensure that his account balance is below the transfer Alice won't be able to re-use the signature anyway.

Reducing Bob timing requirement can be done by allowing him to send a claim request earlier, but either:
1. On transaction pool level having it be pending/low priority until it's valid (if we add SignedExtension to help Alice, we might as well do that for Bob).
2. Queueing up claims and then processing them in `on_initialize`. However this is quite similar to pruning, so I don't know if it makes sense. What could be different though is that instead of tracking transaction ids globally, we let `Bob` prevent himself from  making more swaps. I.e. We let him claim the tokens early, but it means that he is not able to do any swaps for some period of time (`B - current`). This sounds like a worthwhile trade-off though.
