### ISSUE TITLE
Split generic and chain-specific code

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#544]
Some context: https://github.com/paritytech/parity-bridges-common/pull/542#issuecomment-736554190.

We should try to separate chain-specific crates from the generic crates as part of making the repository more developer friendly in case they would want to build their own custom bridges.

I imagine we would have a directory structure which looks somewhat like this:
```
.
├── chains
│   ├── millau
│   ├── polkadot
│   │   ├── primitives
│   │   └── relay
│   └── rialto
│       ├── node
│       ├── primitives
│       ├── relay
│       └── runtime
├── modules
│   ├── pallet-bridge
│   ├── pallet-call-dispatch
│   ├── pallet-currency-echange
│   └── pallet-ethereum
├── primitives
└── relays
```
where everything apart from `chains` does not have any assumptions about the chain it runs on.

**Comment by adoerr** [comment]
Is there a specific reason, why the directory is called `modules` and not `pallets`? AFAIU it's all pallets in `modules`, right?

**Comment by tomusdrw** [comment]
@adoerr good point, I've used the existing directories names for now to better convey the difference, but it would be a good opportunity to re-think naming of the whole structure. I do like `pallets` instead of `modules`.

**Comment by HCastano** [comment]
> Is there a specific reason, why the directory is called `modules` and not `pallets`? AFAIU it's all pallets in `modules`, right?

Back in the day pallets used to be called modules and the original naming in the repo followed that. But yeah, if we want to update to `pallets` there's no real reason we shouldn't

**Comment by EmmanuellNorbertTulbure** [comment]
Closing this for now, will re-open if needed
