### ISSUE TITLE
Token Transfer UI

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#548]
A basic UI allowing to send `source` chain transactions to transfer tokens of the `target` chain (bridge dispatch).

The UI can be connected to both chains (for instance to display token balances) and will have to know how to construct and encode `Call`s of the target chain.

**Comment by tomusdrw** [comment]
Closing:
1. The UI is being worked on in https://github.com/paritytech/parity-bridges-ui and is feature-complete in terms of current bridge design.
2. The Polkadot<>Kusama deployment will not have UI, since it will only be usable by governance, not regular users.
3. In the future Bridge should be integrated with XCM, so a XCM-generic UI should be usable with the bridge instead.

**Comment by hbulgarini** [comment]
🥲
