### ISSUE TITLE
Make ink! and EVM smart contracts capable of speaking to bridged chains

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#555]
The set of components we have right now enables two substrate-based chains to be bridged together if they use FRAME runtime and GRANDPA.

There are smart-contract pallets out there (SEAL & EVM) that could potentially enable smart contracts deployed on such chain to use the bridge as well.

This issue is about researching that possibility and implementing any APIs that might be required for such interop.

CC @pepyakin @Robbepop @sorpaas

**Comment by EmmanuellNorbertTulbure** [comment]
This will be enabled through XCM
