### ISSUE TITLE
Fee top-ups for messages stuck in a lane.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#560]
Currently we heavily rely on on-chain price oracle (#540, #449) to make sure messages that don't pay enough fee (on the source chain) to cover the delivery & dispatch cost (on the target chain) don't get into the queue.

However it may still happen (in case of large price fluctuations) that we will end up with messages that are below profitability point from relayers perspective.

We assume that this can be relayed by either altruistic relayers (see #546) or if the cumulative reward in the lane is high enough (also #546).

It's also assumed that users can "unclog" the lane by putting high-paying messages inside, however we also have a fixed limit of unconfirmed messages in the lane, so at some point it might not be possible to add more rewards.

Hence it would be good to be able to top-up arbitrary message in the lane - i.e. increase the reward for relaying the message, without changing the content.

**Comment by svyatonik** [comment]
> It's also assumed that users can "unclog" the lane by putting high-paying messages inside, however we also have a fixed limit of unconfirmed messages in the lane, so at some point it might not be possible to add more rewards.

This doesn't block us from sending message - it blocks relayer from relaying these messages to the target chain. So you still can 'unblock' the lane by sending empty message and non-zero fee.

**Comment by tomusdrw** [comment]
> This doesn't block us from sending message - it blocks relayer from relaying these messages to the target chain.

Hmm, so on the source chain we don't limit number of pending messages in the lane? I think from the security perspective we should to prevent arbitrary state growth from user-generated data (i.e. the one-time cost doesn't really cover storing the message ad infinitum).

**Comment by svyatonik** [comment]
I don't think that is relevant to the number of messages, right? I mean - we should not be storing even single message for inifinity? 

This could be solved e.g. by replacing instant payment mechanism with some schema where message fee is decaying (burnt) with every block until the fee reaches absolute minimum (e.g. the value returned by `estimate_message_dispatch_and_delivery_fee`). Then  the message payload is replaced with `vec![]`. So relayers will be trying to relay messages asap, because this way they may get maximal reward. At the same time, the fee can't be decayed to the value less than minimal relay cost => this won't stuck the line.

**Comment by tomusdrw** [comment]
> I don't think that is relevant to the number of messages, right? I mean - we should not be storing even single message for inifinity?

Yes, but my point rather is that we shouldn't be assuming that relayers are on line for every active lane id. In an extreme case, even if the fees are crazy high and they would be definitely incentivised to deliver messages there might be external factors that prevent them from doing so - for instance the target chain can reject the delivery & dispatch due to filtering mismatch.

I'd rather include an arbitrary limit that is easily upgradeable by either bridge owner or `root` (the governance).
