### ISSUE TITLE
bench-bot integration

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#587]
Bot: https://github.com/paritytech/bench-bot

That is not super-important for this repo, since we only have testnets here. And accurate weights are not super-important for testnets. But still it may be useful to see how pallet weights are changing just by adding PR comment. Also - if we'll deploy bot on reference machine, we'll be able to at least estimate cost of Polkadot/Kusama transactions before opening PR to these repos.

Right now I'm going to execute benchmarks locally just to generate that `WeightInfo` trait. Polkadot/Kusama have their own bots, so we'll get accurate weights there anyway.

**Comment by tomusdrw** [comment]
Bumping the priority to nice to have, cause I think it shouldn't be that difficult to integrate, and I agree it's really useful even for testnet.

**Comment by svyatonik** [comment]
https://github.com/paritytech/devops/issues/783

**Comment by EmmanuellNorbertTulbure** [comment]
Not relevant for Rialto - Millau
