### ISSUE TITLE
Add more configuration options to runtime module

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#59]
follow up of #45 

 - [x] [Aura configuration](https://github.com/paritytech/parity-bridges-common/blob/74803274f0eef23282357992f756254c671205cf/modules/ethereum/src/lib.rs#L624);
- [x] [Kovan validators configuration](https://github.com/paritytech/parity-bridges-common/blob/74803274f0eef23282357992f756254c671205cf/modules/ethereum/src/lib.rs#L638);
- [ ] [Transaction pool configuration](https://github.com/paritytech/parity-bridges-common/blob/74803274f0eef23282357992f756254c671205cf/modules/ethereum/src/lib.rs#L751);
 - [ ] [Priority of unsigned transactions](https://github.com/paritytech/parity-bridges-common/pull/45#discussion_r402960072);
 - [ ] [Longevity of unsigned transactions](https://github.com/paritytech/parity-bridges-common/pull/45#discussion_r402960366);
 - [ ] [Prefix for unsigned transaction tags](https://github.com/paritytech/parity-bridges-common/pull/45#discussion_r402971379);

**Comment by tomusdrw** [comment]
Obsolete by #1210
