### ISSUE TITLE
A Element room is necessity?

### ISSUE THREAD

**Issue by AsceticBear** [paritytech/parity-bridges-common#592]
Hi, Core coders in this repo. Thanks for all your excellent work about the bridges and relayer.  

Sometimes, I(others) would like to ask for some information about the bridges design or something else, but no chat channel can be found all the network. So, I make this advice that it would be better if there is an element zoom for the person who wants to use 
 the bridges or contribute pull quest for exchanging ideas.

Just like [Frontier Room](https://app.element.io/?pk_vid=6961ca0f7c45f8bf16052310122d2437#/room/#frontier:matrix.org)  or [Substrate Technical](https://app.element.io/?pk_vid=6961ca0f7c45f8bf16052310122d2437#/room/#substrate-technical:matrix.org)

**Comment by tomusdrw** [comment]
Hi @AsceticBear I think it would be best to join [`#bridges:web3.foundation
`](https://matrix.to/#/!dOiGCcBecwSGXtifov:web3.foundation?via=web3.foundation&via=matrix.org&via=matrix.parity.io) room.
It's not very active, but we hope it would change soon :)

Might be worth adding this to the README as well (PR welcome:))
