### ISSUE TITLE
Make relay (easy) configurable for other chains

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#61]
original comment: https://github.com/paritytech/parity-bridges-common/pull/58#discussion_r404764786

The problem is that we can't (at least I do not know how atm) make relay generic over runtime/chain. That's why if we're going to point it to other chain, it would need to be reconfigured and rebuilt before any transaction will be submitted.

The only way I could think of, is to extract everything that is runtime/chain specific (including crypto type) to separate file, like [this one](https://github.com/paritytech/secret-store/blob/master/bin/substrate/src/runtime.rs#L17). This also must be noted in crate' readme.

**Comment by tomusdrw** [comment]
Related #153

**Comment by tomusdrw** [comment]
Closed via #849
