### ISSUE TITLE
Replay-protecting variant of CallOrigin::TargetAccount

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#614]
Our current assumption with `CallOrigin::TargetAccount` is that both the private key on the source chain and the target chain is controlled by the same entity. This means that the only way to replay the message signed with the target key is to send it again with the source key.

In some scenarios it might not be desirable though, and to protect the users we should figure out how to prevent replaying such messages.

Explore possibilities:
- [ ] use source account nonce?
- [ ] explicit nonce mechanism? (`Map<source_account_id++target_account_id, Nonce>`)
- [ ] message nonce? (index in the lane?)
- [ ] recent block hash?

**Comment by tomusdrw** [comment]
A combination of source account nonce + source block hash seems interesting to me as it doesn't require any extra storage entries. Block hash or mortality (#622) is required to prevent replays in case source account goes below ED (be careful cause it may happen during fee payment!) and have it's nonce re-set.

**Comment by svyatonik** [comment]
more details: https://github.com/paritytech/srlabs_findings/issues/42

**Comment by adoerr** [comment]
Filing some comments from @tomusdrw so they don't get forgotten

> We should add spec_version/tx_version and bridge_id even for #614 (and that's what #42 is about)

> Another angle is mortality of calls, that's something that is also partially related and worth implementing. So if we change the call to actaully be:
let call_object = { call, spec_version/tx_version, mortality }; then we should change the signing payload to bridge_id ++ source_account_id ++ call_object.

**Comment by svyatonik** [comment]
irrelevant after #1376
