### ISSUE TITLE
Accumulate relayer rewards

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#619]
Instead of transfer rewards directly to relayers with every confirmation we should instead have them accumulate in the relayers fund and then have relayers to withdraw whenever they want (or when some threshold is reached). This will minimize the number of small transfers. However since initially we expect only a few relayers, this shouldn't be a real-world problem.

**Comment by EmmanuellNorbertTulbure** [comment]
Already done!
