### ISSUE TITLE
Allow Root to use CallOrigin::SourceAccount

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#620]
Currently `SourceAccount` call origin can only be used by regular accounts, but `Root`/`Runtime Dev` can use it anyway by crafitng a special origin when calling that function. This is cumbersome to use and we should consider allowing Root to simply use any `SourceOrigin` it wants.

**Comment by kaichaosun** [comment]
I'd like to work on this issue, 
when say `SourceOrigin`, do you mean any account, pallet origin from the source chain?
If yes, I'll probably add a `SourceChainAccountId` to `SourceRoot`, hope I'm in the right direction.

**Comment by tomusdrw** [comment]
@kaichaosun thanks for looking into this. Adding account id to `SourceRoot` is one of the options indeed, I was thinking more about changing this verification [here](https://github.com/paritytech/parity-bridges-common/blob/fc5cf7dd9e8c0ecf8c11956b8851e44a0c1af639/modules/dispatch/src/lib.rs#L355) to allow `Root` as well.

@svyatonik which variant do you prefer? I'd leave `SourceRoot` intact, since even if we add account id there the root account can do whatever it wants via `sudo_as`, hence I'm not sure if it gives us much on the target chain side to distinguish between `SourceAccount(account)` and `SourceRoot(account)` and it does complicate the handling a bit.

**Comment by kaichaosun** [comment]
Thanks for pointing out both options, @tomusdrw .
It's much clean by changing the verification logic at the source chain side. 
But at target chain side, it loses information whether `SourceAccount(account)` is from a real account or assigned by the root.
Are there scenarios that need to distinguish them? Another option could cover this requirement is adding an extra field `forced_account` to `SourceAccount(account)`, this may be overkill at current stage.
