### ISSUE TITLE
Update docker/build-push-action to V2

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#630]
A newer version of the [GitHub Action we use](https://github.com/docker/build-push-action) to build and publish Docker images is available. It includes some breaking changes, so somebody will manually have to update our publishing jobs.

Upgrade notes can be found [here](https://github.com/docker/build-push-action/blob/master/UPGRADE.md).

**Comment by TriplEight** [comment]
we use buildah now

**Comment by HCastano** [comment]
> we use buildah now

Just want to add the switch to `buildah` happened in #779.

**Comment by TriplEight** [comment]
I would never even know about this issue if wouldn't find it randomly. The `devops` label doesn't mention me or the team.

**Comment by tomusdrw** [comment]
Note the label does not mean we expect the devops team to work on that though. There is a bunch of "devopsy" tasks that the team is capable doing on our own.
