### ISSUE TITLE
Relay is losing connection to Substrate node when transaction is submitted

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#741]
There's some connection-related issue with tonight deployments. Following pattern repeats in millau-to-rialto messages relay logs:
```
[1;38;5;8m2021-02-18 09:00:22 +0000[0m [38;5;14mDEBUG[0m [38;5;8mbridge[0m Received nonces from Rialto::ReceivingConfirmationsDelivery: SourceClientNonces { new_nonces: 978..=977, confirmed_nonce: None }
[1;38;5;8m2021-02-18 09:00:22 +0000[0m [38;5;14mDEBUG[0m [38;5;8mbridge[0m Asking Rialto::ReceivingConfirmationsDelivery to prove nonces in range 866..=977 at block HeaderId(2388, 0xf23b8a49a96c5f05629491fa2e571cab99140e05bb8419a3b59f12e96b567f4b)
[1;38;5;8m2021-02-18 09:00:22 +0000[0m [38;5;14mDEBUG[0m [38;5;8mbridge[0m Received best nonces from Millau::ReceivingConfirmationsDelivery: TargetClientNonces { latest_nonce: 865, nonces_data: () }
...
[1;38;5;8m2021-02-18 09:00:22 +0000[0m [38;5;14mDEBUG[0m [38;5;8mbridge[0m Received proof for nonces in range 866..=977 from Rialto::ReceivingConfirmationsDelivery
[1;38;5;8m2021-02-18 09:00:22 +0000[0m [38;5;14mDEBUG[0m [38;5;8mbridge[0m Going to submit proof of messages in range 866..=977 to Millau::ReceivingConfirmationsDelivery node
[1;38;5;8m2021-02-18 09:00:22 +0000[0m [1;38;5;9mERROR[0m [38;5;8mbridge[0m Error submitting proof Millau::ReceivingConfirmationsDelivery: Request(TransportError(Custom { kind: Other, error: "background task closed" })). Going to restart
[1;38;5;8m2021-02-18 09:00:32 +0000[0m [38;5;14mDEBUG[0m [38;5;8mbridge[0m Restarting relay loop
...
```

So it seems that everything works fine - we are receiving data from both Rialto and Millau nodes. Then, suddenly, when proof is submitted to the Millau node, something breaks in jsonrpsee ("background task closed") and we restart the loop. After restart, everything repeats again. There's nothing strange in `millau-node-bob` logs when this happens. We have no `jsonrpsee` + `soketto` logs enabled for relayer, so there's nothing to work with :/

The "solution" is:
1) #661 
2) enable transport-related logs for message relays.

This must be done before P+K release

UPD: just trying to log how often this issue happens
1st reproduce: 18.02
2nd reproduce: 04.03

**Comment by svyatonik** [comment]
Some more info, missing from description:
1) "background task closed" appears after we see some unmatched error [here](https://github.com/svyatonik/jsonrpsee/blob/shared-client-in-rpc-api/src/client.rs#L429). In our jsonrpsee fork we treat all errors that have no associated request id as "connection errors", thus stopping the background thread and forcing relay loops to restart;
2) possible unmatched errors that have caused this are::
2.1) `DuplicateSubscriptionId`, `SubscriptionIdParseError`, `UnknownSubscriptionId`  - are unlikely to happen, because in messages relay we have no any subscriptions;
2.2) `RequestIError(None)` and `Inner(Some)` - can't happen in ws client (according to the code);
2.2) `NullRequestId` and `UnknownRequestId`;
2.3) `Inner(None)` - is, most likely, the cause of issue here.

So the issue is either on relay side (`jsonrpsee` -> `soketto` -> `async_std::net`), or on the node side (`jsonrpc` + `parity_ws`). I've already reverted #742 (thought it may be a cause of performance issues we have had), so we won't get normal logs even if issue repeats. Locally I was trying to reproduce it for two nights in a row, but everything runs smoothly. So I'm going to unassign myself from this issue for now, as there's not much I can do.

**Comment by niklasad1** [comment]
It might be https://github.com/paritytech/jsonrpsee/issues/154 that you run into, it's fixed on master.
