### ISSUE TITLE
Use self-hosted runner for Docker image build.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#747]
Seems that building Docker images is quite heavy (especially on disk space), we might consider using self-hosted runner just for this one job - it's being run only nightly anyway, so it shouldn't be a big deal.

Failing build: https://github.com/paritytech/parity-bridges-common/runs/1931930586?check_suite_focus=true

**Comment by TriplEight** [comment]
also https://github.com/paritytech/parity-bridges-common/actions/runs/587642086

**Comment by TriplEight** [comment]
closed with https://github.com/paritytech/parity-bridges-common/pull/766
