### ISSUE TITLE
Assume Scheduled Change Delay is Zero

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#760]
When checking headers for scheduled authority set changes in the import pipeline of the
bridge pallet we have some small checks which use the `delay` field of [GRANDPA's
`ScheduledChange` struct](https://github.com/paritytech/substrate/blob/master/primitives/finality-grandpa/src/lib.rs#L82-L87).

I recently learned that it is safe to assume that as long as GRANDPA has not stalled the
`delay` will [always be zero](https://github.com/paritytech/substrate/blob/master/frame/grandpa/src/lib.rs#L611-L615).

We can use this fact to check for a non-zero delay in any header which schedules changes
and reject such headers. We want to reject these headers since they indicate that either:
a relayer is submitting invalid headers, or a forced change has occured. The former
should not be accepted, and the latter can only be remedied by the chain's governance
anyways (since the pallet wouldn't be able to verify finality for any future headers).

**Comment by svyatonik** [comment]
I also suggest to do two things:
1) optionally - remove all delay traces from our pallet code - like we don't need scheduled changes anymore. This will simplify code + we'll get rid of extra storage entries;
2) also reject headers with `ConsensusLog::ForcedChange` digest - we can't follow the finalized chain after such digest anyway + we don't need all headers.

**Comment by tomusdrw** [comment]
@HCastano is this already done?

**Comment by HCastano** [comment]
@tomusdrw yep, this should've been closed with #783.
