### ISSUE TITLE
Use SetId Field from ConsensusLog

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#788]
Sometime in the future GRANDPA is going to start including the `set_id` it expects in the
`ScheduledChange` digests it issues. We should use this field instead of manually
computing the expected `set_id` ourselves.

With this change we'll also be able to check that `set_id` is actually increasing
monotonically, ensuring that authority set handoffs are happening correctly.

**Comment by adoerr** [comment]
You have an issue or code permalink where this GRANDPA change could be tracked? This is useful for BEEFY as well.

**Comment by HCastano** [comment]
> You have an issue or code permalink where this GRANDPA change could be tracked? This is useful for BEEFY as well.

@andresilva do you have an issue made, or is it just in your head at the moment?

**Comment by tomusdrw** [comment]
> I am thinking of changing this to ForcedChange(SetId, N, ScheduledChange<N>). In which case, for forced changes we'd unconditionally apply the set_id provided in the digest rather than doing + 1. We'd still keep the old variant as OldForcedChange(N, ScheduledChange<N>) since we need this for backwards compatibility.

Sounds like a good idea to me. Indeed if the `set_id` is part of the signed payload in justification this should be fine.
