### ISSUE TITLE
Missing Code of Conduct

### ISSUE THREAD

**Issue by BobinMathew** [paritytech/parity-bridges-common#789]
I see that your repo is missing its Code of Conduct. Adding a Code of Conduct improves your community profile
Cant I propose a Code of Conduct?

**Comment by HCastano** [comment]
Hey! Adding one sounds reasonable to me. I would use the [one from Substrate](https://github.com/paritytech/substrate/blob/master/docs/CODE_OF_CONDUCT.md) since that's already "Parity blessed".

**Comment by HCastano** [comment]
Closed by #791.
