### ISSUE TITLE
Node with millau-runtime crashes after ~60sec 

### ISSUE THREAD

**Issue by MaciejBaj** [paritytech/parity-bridges-common#794]
After a successful build & start of a node that runs with `millau-runtime` (0.1.0) and connects a bridge to Rialto (not initialized), the node crashes regularly after approx 60 seconds with the following err (could post the whole stack trace if that helps):  

```
Thread 'tokio-runtime-worker' panicked at 'Unexpected Either::Right on enabled `inject_listen_upgrade_error`.', /Users/macio/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-swarm-0.27.1/src/toggle.rs:288

This is a bug. Please report it at:

        https://github.com/paritytech/parity-bridges-common/

```
I use `nightly-2020-10-01-x86_64-apple-darwin` and that happens to me with the code from approx ~February 15th 
``
78b843d (HEAD -> master, origin/master, origin/HEAD) Rework relay CLI a bit (#734)
``

Was wondering maybe you're experiencing the same and there's a quick aid for this? Cheers

**Comment by tomusdrw** [comment]
This seems like some libp2p issue, we have updated substrate recently, do you mind testing with latest master?

Also please enable `RUST_BACKTRACE=full` and provide the full backtrace as well.

**Comment by HCastano** [comment]
@MaciejBaj I'm gonna close this for now. Ping us here if you have more logs indicating that this is still an issue
