### ISSUE TITLE
Best Finalized block is empty in polkadotjs.

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/parity-bridges-common#836]
After the latest changes to the types.json files , the best finalized block query retrieves an empty result.

**Comment by svyatonik** [comment]
Which runtime API do you use? Could it be because we have recently abandoned our substrate pallet? Now you need to read best finalized block using finality verifier pallet.

**Comment by hbulgarini** [comment]
I don't know exactly the runtime API but i'm running the updated docker images so i suspect that i'm using the latest and most updated version.

At the momento from the JS point of view i'm getting the value from the following code:
```
   api.query.BridgeMillau.bestFinalized((res: CodecHeaderId) => {
      const bestBridgedFinalizedBlock = res.toString();
      api.query.BridgeMillau.importedHeaders(bestBridgedFinalizedBlock, (res: any) => {
        if (res.toJSON()) {
          setImportedHeaders(res.toJSON().header.number);
        }
      });
    });
```

So should i get the value from a different object?

**Comment by tomusdrw** [comment]
Yes, this should be coming from [this pallet](https://github.com/paritytech/parity-bridges-common/blob/b7410cad7ee80cde1d64327190842e768328b855/bin/rialto/runtime/src/lib.rs#L483) now. And the storage item you want to query is [this one](https://github.com/paritytech/parity-bridges-common/blob/b7410cad7ee80cde1d64327190842e768328b855/modules/finality-verifier/src/lib.rs#L232).
Note this might get renamed pretty soon, so please try to follow the PRs. Also for anyone changing this - please ping Hector :)

**Comment by HCastano** [comment]
I'm gonna close this since you're using an old pallet. Feel free to re-open if something similar occurs with `pallet-bridge-grandpa`
