### ISSUE TITLE
Fix `CliChain` abstraction

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#854]
Follow up of #849.

After the PR lands, `CliChain` trait includes things like `type MessagePayload` and `fn encode_call/encode_message`. The problem with this abstraction is that it's not generic enough (see #853), it only works cause currently we don't have a bridge which can send messages to two different target chains.

The goal is to fix this abstraction - most likely it's not `CliChain` responsibility at all I think this can be nicely generalised with the `select_bridge` macro and some structural code unification.

**Comment by svyatonik** [comment]
Irrelevant
