### ISSUE TITLE
Add CLI tests for other `Call` variants

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#863]
Follow up on #859

Context: https://github.com/paritytech/parity-bridges-common/pull/859/files#r606399268

**Comment by oxarbitrage** [comment]
Hey, i was wondering if this was resolved fully by https://github.com/paritytech/parity-bridges-common/pull/868 or if there are still tests to be done.

**Comment by tomusdrw** [comment]
So AFAICT there are tests for `Remark` and `Transfer`, but we still have `Raw` and `BridgeSendMessage` in the enum, so might be worth adding tests for these.

**Comment by svyatonik** [comment]
irrelevant after #1376
