### ISSUE TITLE
Runtime upgrade verification

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#883]
Currently when the target chain receives a message and attempts to dispatch it, it has to trust that the `Origin` was correctly verified/generated on the source chain.
This obviously requires manually reviewing the runtime code and maintaining trust between source and target chain. However currently the target chain can't verify what source-chain runtime generated incoming message (i.e. we don't know if the code didin't change in the meantime).

In some cases it might be desirable to require target chain runtime to explicitly establish trust with every new runtime version of the source chain. It's not that much of a security measure (assuming source chain is compromised it can pretend the runtime upgrade didn't happen), but the target chain dispatch mechanism might benefit from being able to distinguish legit runtime upgrades.

To make this possible the dispatch pallet could periodically receive storage proofs for some well known keys (`:codehash` (when introduced) or `:code` (but somehow compressed), or best simply runtime version). Receiving such proof would update internal knowledge of the source chain runtime and could be used to filter out incoming calls. It should probably be message relayers responsinble for doing that, or we might introduce another role for this. Depending on the guarantees we want to provide it might make sense to incentivise this as well.

**Comment by acatangiu** [comment]
With XCMv3 design, this is no longer an issue iiuc. @bkontur please reopen if I'm mistaken.
