### ISSUE TITLE
Meta: Support running bridge on a parachain.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#884]
Currently the `pallet-bridge-grandpa` and `pallet-bridge-messages` pallets (and corresponding relayers) assume that we get storage & finality proofs of the same chain we are deployed on. In case of running within a parachain the situation is going to be a bit different, and we need to explore how to best enable both use cases.

**Comment by tomusdrw** [comment]
Thoughts from @svyatonik 
> 1. proofs that are now used in the messages pallet will change from "hash(header) + storage_proof(message)" to "hash(relay_header) + relay_storage_proof(parachain_header_hash) + parachain_header + parachain_storage_proof(message)". This is because at least now parachain clients do not have any persistent proofs (like GRANDPA justifications) of their blocks finality && it looks like proving the parachain head using relay chain storage is the only "standard way" (we may of course customize "bridges parachain" to hold this information + make another relay, but it seems redundant);
> 2. since we'll need proofs from both relay- and para- chains, our relayer would need to connect to both chains;
> 3. since we need to connect to both chains, maybe it's a good idea to introduce RPC methods like "state_proveStorage(<storage-key>)" to the Substrate codebase + adding them to Polkadot and Cumulus (instead of custom messages RPCs that we have now);
> 4. I haven't found any estimations on how often relay chain will ask for/accept new parachain blocks (I guess it'll also probably be increased proportionally to number of parachains). But right now we live in a world with almost instant finality => the message route is quite short. If relay chain will be finalizing bridge parachain blocks with significantly slower rate, it may affect applications that will be based on our bridge;
> 5. (not about the bridge, but about our deployments) from what I understand, Interlay guys already have their pallets integrated into Cumulus runtime. So probably we'll also need to do that. But it should be done after deploying on relay chains, as a preparation for "bridges parachain" - I don't want to have two Millau and two Rialto runtimes/nodes.

**Comment by svyatonik** [comment]
#1068 #1199 #1218
