### ISSUE TITLE
Return actual post-dispatch weight from messages calls

### ISSUE THREAD

**Issue by svyatonik** [paritytech/parity-bridges-common#916]
All current `pallet-bridge-messages` benchmarks are designed to be the worst-case benchmarks and their results are used by the weight formula. Where data that affect weight is directly accessible from the call arguments (e.g. message size, proof size), weight formula uses this information. But when data is only accessible during execution (e.g. we need to read message first, so its size is unknown from the args), then the weight formula would use worst-case arguments (e.g. maximal possible message size). Recently I've discovered [this](https://github.com/paritytech/parity-bridges-common/issues/561#issuecomment-822357701) and there's a bunch of things that may be improved. Some (but probably not all) examples include: 
- [increase message fee weight](https://github.com/paritytech/parity-bridges-common/blob/89a76998f93c8219e9b1f785dcce73d4891e7068/modules/messages/src/weights.rs#L91) is quite a large because benchmark is written for the worst case, when message size is maximal. We may refund submitter if message has lesser size;
- we assume that when message is sent, [maximal allowed number of messages is pruned](https://github.com/paritytech/parity-bridges-common/blob/89a76998f93c8219e9b1f785dcce73d4891e7068/modules/messages/src/benchmarking.rs#L121). But it isn't true - we can refund submitter if we have pruned less-than-max number of headers.

**Comment by tomusdrw** [comment]
I've bumped priority a bit, cause I think it would be awesome to do right after production deployment to optimize the costs.

**Comment by svyatonik** [comment]
Closed by #1062 and #1066
