### ISSUE TITLE
Support instances of `pallet_bridge_grandpa` in runtime common

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#941]
Seems that we fallback to `DefaultInstance` here: https://github.com/paritytech/parity-bridges-common/blob/a13ee0bc355560d25a4518a98f1472571a8b66f4/bin/runtime-common/src/messages.rs#L359

We should be supporting any instance of `pallet_bridge_grandpa::Config`.

**Comment by svyatonik** [comment]
seems to be closed by #942
