### ISSUE TITLE
Sending transactions from PJS apps is broken

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#949]
Seems that we can't send transfers in PJS apps any more, it errors out with "Transaction has invalid signature" on both Rialto and Millau.

It's either some issue with custom types, or some runtime incompatibility.

**Comment by tomusdrw** [comment]
As a workaround it might be worth adding regular `transfer` sub-command to our CLI to fund accounts. Also related #943

**Comment by tomusdrw** [comment]
Update to latest substrate might potentially help as well.

**Comment by vmarkushin** [comment]
With Rialto, it works fine for me, but with Millau, PJSapps produces: `createType(CodecHash):: Expected at least 64 bytes (512 bits), found 32 bytes`. Seems like because of the different hashing algorithm (`BlakeTwoAndKeccak256`).

**Comment by tomusdrw** [comment]
Yeah, it seems this was fixed with Substrate upgrade. Millau not working is a known issue, cause indeed there is no way for PJS/apps to configure custom hasher as of now.

**Comment by svyatonik** [comment]
seems to be fixed

**Comment by svyatonik** [comment]
seems to be fixed
