### ISSUE TITLE
Consider reducing fee for submitting valid finality proofs.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#954]
Currently calling `pallet_bridge_grandpa::submit_finality_proof` requires the relayer to pay full cost of the transaction.
We may consider reducing these costs (maybe even to 0), under some very detailed assumptions (modelling required):

1. The finality proofs are correct & useful.
2. The finality proofs are within expected rate (i.e. the cost should be larger for submitting them too often).

**Comment by svyatonik** [comment]
I think we may close it now, after #1127 ? Please reopen if you think we should also reduce fee for non-mandatory submissions
