### ISSUE TITLE
Expose bridge Ids in RPC system.properties()

### ISSUE THREAD

**Issue by hbulgarini** [paritytech/parity-bridges-common#956]
Related to https://github.com/paritytech/parity-bridges-ui/issues/86

We need to able to read the bridges Id from the RPC call. 

At the moment `api.rpc.system.properties()` is not retrieving the corresponding `bridgeId`  key.

Please choose `Get system information`  from the dropdown: [Rialto Javascript](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fwss.rialto.brucke.link&types=eNq9V19v2zYQ%2FyqBnlLAARanCbKuKJAm3eKtqYM4yx6GQmCks8xVJlWSSucF%2Fu67IymRlOw%2BtX0xxPvz4x35uzv6OTs6Os5eZTe8rll7cL9pQGcTv3zLaiYKQHV79jJIa1l8umZ6hfLr0%2BNpqvjQrh9BDVyugZUkfM4apkCY3LsPASeZ6Nwv5bphhXk9gn6DVtowA7mS0uwEgX%2BN4kLzQu%2B3KXkFOqiu3HLbRezXGHEtK41mD1D4WJxqZmD9ZmhPQvLJAfOgj7lZ2WzIuz2n0C9as5KKGw76csVERadL2k6%2BmZVk5nT6XnG425fCAlj98BOq%2FAd6SaFB6JYCDt%2FO0tvh6lbBXSsMX9Pe0WKL2RwdTVF4x1ltZM8Gt4zYcDw9D%2BKYDtPTs1QR6HBCRHGafXQYAu6gwwh6RIcxyJgOY5ueDk4V6JCsUzrEqp4OQ%2BH3osM4he9DhxN3%2BGspDoynw0VZKtAEelEUEq1nJUrfS%2FmpbRayVZYjscp%2FL3glbPo3bW24X2E0DRQPoDSXIvAEarYBhd4pkoMPklQ7WzdSGSgDv1b%2BK3ureFn1mkmm4HPLMYv8n1YbvuQFM27%2FRynpULjOl1ywmv8HtIuXaoyZ1fnK0XXekM9rD91fhaVBf38LsLRh4Z4p6E77niOrEBdMzmkftMZM0N%2Fm9nd7%2FsvBy4%2BUmUCOY%2FFZsTtuJqLVDd4Hq%2BCDTNq1E1qrw1k5OUDxiyD%2FAzaW0AjkNveQWHUE84ouKoalqMQjHnbpb2d4%2Bk5JKFfMMMJWzrArmMMYb3KQrvorf0GEr5k2eSHFkqs1lLmNaEdA89aMNq2xGaBzBUgv%2FNzjTFtYOwUF8Kf9ZrIuyawVjWrFV0Lx6y6Khm1qyehYveLWCybZEsj%2FV%2FwNbp027g2eWPOGfW7hktVUs0Hbpe4BCM6BBlUP%2BpxpLLL8qa%2ByuOYm2Rfg1Yqayl%2FuA5NWvOJkSNvO3WKSFS6GcVyYR2QYdzxXsL5nHRL77pmqwHjikHBQ08iL0B6iBTOtAgJI7CmXQU%2BgvhV3mDicd%2BX09PT45zCqFmogeFeUGi%2FQ1t7JyUeH5o5Y3%2BL4WM6XBPToziB3DabrCMNWYGeTVOibN%2BTrL3DhZBbODQ5io6ALTGtQ51j2yk7%2FlJReCyIiWM%2FEIXxCmy6XK6iR9Wrz43LCyP4UCr4wVULXQvSCRjdt3vYqrEirw%2Bxwbtt%2BOch%2B7XPIuch9eZIttrOhpZEG%2B3Vnv%2BOsLugc0dXG3VE0lFToKaMmGQp8WG4Ii2O0wKHJbe%2FHK0TGf%2BU8vUH%2F2IlN%2FAMqGSldNXiantkREb0YOvpOSW6roEwCasIiitSPNw%2B8YzecinbiRhtR4X%2FTPPFcu4C6qTFIwI7X3xQTZcN%2BT4c3Dhy6h34A9kn6GCfZk8Sen9MkxUt33KItkteB3cC10%2FThix25fwKPNNErePw0S5%2FC4%2Bdx3%2BtjmPGDf8d5JWZDtO4dlP4LQ3YyxdZgBr3RhXUvnTG%2BF%2F24uLMV6h792%2B32f6jq39I%3D#/js)

**Comment by tomusdrw** [comment]
Closed via https://github.com/paritytech/parity-bridges-common/pull/951
