### ISSUE TITLE
Same `source_transactions_author` type in different chain

### ISSUE THREAD

**Issue by fewensa** [paritytech/parity-bridges-common#967]
I think this is a bug.

https://github.com/paritytech/parity-bridges-common/blob/84360731669fe8d4ab050583e7191108af3a3341/relays/bin-substrate/src/chains/millau_messages_to_rialto.rs#L62

https://github.com/paritytech/parity-bridges-common/blob/84360731669fe8d4ab050583e7191108af3a3341/relays/bin-substrate/src/chains/rialto_messages_to_millau.rs#L62

In different chain, there returned type is same with `bp_rialto::AccountId`, although, the `bp_rialto::AccountId` and `bp_millau::AccountId` type are same, but I think there should be change to right type.

**Comment by HCastano** [comment]
Yep, the one from `millau_messages_to_rialto` should be `bp_millau::AccountId`. Please open a PR 😄

**Comment by svyatonik** [comment]
closed by #968
