### ISSUE TITLE
Can I start multiple substrate-relay between same bridge?

### ISSUE THREAD

**Issue by fewensa** [paritytech/parity-bridges-common#978]
read best finalized header
https://github.com/paritytech/parity-bridges-common/blob/e1d1f4c6ff34d73d8b328fd8db358405b2949707/relays/bin-substrate/src/messages_source.rs#L130-L134

`submit_signed_extrinsic`
https://github.com/paritytech/parity-bridges-common/blob/e1d1f4c6ff34d73d8b328fd8db358405b2949707/relays/client-substrate/src/client.rs#L241-L259

`insert_header`
https://github.com/paritytech/parity-bridges-common/blob/e1d1f4c6ff34d73d8b328fd8db358405b2949707/modules/grandpa/src/lib.rs#L426-L443

There are atomic operate? If start two or more substrate-relay client, will there be a problem?

**Comment by HCastano** [comment]
Yes, you can have multiple relayers. No, they're not atomic. 

Each relayer will be its own process, so it has no clue what other relayers are doing. This can lead to situations where multiple relayers try and submit the same finalized block to the target chain and one ends up getting rejected for submitting stale data (this also means it has to eat the transaction costs).

How likely is this in practice though? That's unclear at the moment. Maybe you can do some testing and let us know 😉 

Do you have any better insights than me on this @svyatonik?

**Comment by svyatonik** [comment]
> Each relayer will be its own process, so it has no clue what other relayers are doing. This can lead to situations where multiple relayers try and submit the same finalized block to the target chain and one ends up getting rejected for submitting stale data (this also means it has to eat the transaction costs).

That's correct. Anyone could start its own relayer and start submitting headers. We don't have any restrictions on that. The general vision is that you're not incentivized to run headers relayer at all. Instead you should be running applicataion-level relay (e.g. messages relay) where relayer is paid for its work. And applications require headers to be submitted, so you have to submit headers only when it is required by your application. The same problem is also actual for applications relays, though - e.g. if you'll start several messages relayers, then they will start submitting the same transactions. There have been some ideas (they're somewhere in the issue tracker) on how to avoid that, but they're not implemented now.

**Comment by HCastano** [comment]
@fewensa I'm gonna close this since I think it's been answered. Feel free to re-open if you think otherwise
