### ISSUE TITLE
Add Dedicated Release Branch

### ISSUE THREAD

**Issue by HCastano** [paritytech/parity-bridges-common#985]
This is kinda a follow up to https://github.com/paritytech/ci_cd/issues/136.

After a few discussion with @s3krit, @TriplEight, and @tomusdrw we've decided that the deployment pipeline for the bridge relayers should live as part of the `parity-bridges-common` repo instead of the Polkadot repo.

While having the binaries built as part of the Polkadot repo would've been nice, the problem with it was that we would've had no ability to use GitHub Releases and its respective changelogs. While we could've kept a changelog in this repo, I think it would've added unnecessary complexity/confusion for us and any users looking for binaries.

In order to have the releases here we will need to maintain a new `release` branch alongside `master`. This `release` branch will need to be kept up to date with the bridges code in the Polkadot Subtree. While this can be done manually at first, we should aim to automate this in a similar fashion to the Polkadot and Substrate PR companion system works. One difference here will be that we should only run this on `tags` and not on every commit.

**Comment by tomusdrw** [comment]
We currently have `polkadot-staging` that serves as a reference for the polkadot subtree copy.
