### ISSUE TITLE
Support fee payment in non-native tokens.

### ISSUE THREAD

**Issue by tomusdrw** [paritytech/parity-bridges-common#992]
Currently when sending the messages the fee is assumed to be payed in native token of the source chain and we rely on the price oracle to know exactly how it maps to the target chain tokens.

Given the chain can support multiple tokens, it would be good to introduce a possibility to pay in any of them. The rules may vary per-lane (i.e. some lanes only supporting native tokens, etc). Each of the tokens may have different rules how to map it to target chain tokens.

Ideally the user would pay fees in wrapped target-chain tokens, so there is no conversion needed and we don't have to rely on the price oracle at all.

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/decentralized-dot-eth-bridges-a-comparison-thread/777/12

**Comment by svyatonik** [comment]
We are no longer taking any fees on chains where our pallets are deployed (bridge hubs), so it is irrelevant
